import {
  CompanyProfile,
  IndustryProfile,
  IndustrySlug,
  DealItem,
  ExecutiveProfile,
  RadarItem,
  BusinessMetricItem,
  BusinessInsightItem,
} from './business-intelligence-types';
import { bvbCompanies } from './bvb-data';

// Map BVB companies to expanded CompanyProfile format
export const companiesData: CompanyProfile[] = [
  ...bvbCompanies.map((c) => ({
    id: c.id,
    slug: c.slug,
    symbol: c.symbol,
    isin: c.isin,
    cui: c.cui,
    name: c.name,
    logo: null,
    coverImage: c.coverImage,
    industry: c.sector,
    industrySlug: (c.slug.includes('banca') || c.slug.includes('bursa')
      ? 'banking'
      : c.slug.includes('hidro') || c.slug.includes('petrom') || c.slug.includes('romgaz')
      ? 'energy'
      : c.slug.includes('one')
      ? 'real-estate'
      : 'technology') as IndustrySlug,
    headquarters: c.headquarters,
    ownership: c.symbol === 'TLV' ? 'Piața liberă BVB (Pilon II & Privat)' : 'Capital Privat & Public (BVB)',
    management: `Consiliu de Administrație & CEO ${c.ceo}`,
    ceo: c.ceo,
    revenue: c.revenue,
    revenueValue: c.revenueValue || 1000000000,
    profit: c.netIncome,
    profitValue: c.netProfit || 200000000,
    employees: c.symbol === 'TLV' ? 10500 : c.symbol === 'H2O' ? 3400 : c.symbol === 'SNP' ? 12800 : c.symbol === 'ONE' ? 450 : 5800,
    assets: c.totalAssets ? `${(c.totalAssets / 1000000000).toFixed(1)}B RON` : 'N/A',
    assetsValue: c.totalAssets || 0,
    growth: '+12.5% YoY',
    marketCap: c.marketCap,
    peRatio: c.peRatio,
    dividendYield: c.dividendYield,
    investments: 'Proiecte majore de extindere și tranziție verde',
    acquisitions: 'M&A strategic pe piața locală',
    competitors: ['Piața financiar-bancară', 'Operatorii regionali de energie'],
    recentDevelopments: c.corporateEvents.map((e) => `${e.date}: ${e.title}`),
    businessModel: c.description,
    risks: ['Volatilitatea prețurilor la energie', 'Modificări ale cadrului de impozitare'],
    opportunities: ['Finanțări europene PNRR', 'Creșterea bancarizării și a pieței de capital'],
    timeline: c.timeline,
    asOf: c.asOf,
  })),

  // Additional major verified Romanian corporate leaders
  {
    id: 'comp-unicredit-ro',
    slug: 'unicredit-bank-romania',
    symbol: 'UCB',
    cui: 'RO 361536',
    name: 'UniCredit Bank România S.A.',
    logo: null,
    coverImage: '/fallbacks/story-banking-finance.jpg',
    industry: 'Servicii Financiare & Bănci',
    industrySlug: 'banking',
    headquarters: 'București, Bd. Expoziției nr. 1F',
    ownership: 'Grupul UniCredit (Italia)',
    management: 'Comitet Executiv & Board',
    ceo: 'Mihaela Lupu',
    revenue: '3.45B RON (FY 2025)',
    revenueValue: 3450000000,
    profit: '1.28B RON (FY 2025)',
    profitValue: 1280000000,
    employees: 3300,
    assets: '68.5B RON',
    assetsValue: 68500000000,
    growth: '+14.2% YoY',
    investments: 'Finanțare 100M EUR BEI pentru IMM-uri românești',
    acquisitions: 'Fuziunea cu Alpha Bank România',
    competitors: ['Banca Transilvania', 'BCR', 'BRD Group Société Générale'],
    recentDevelopments: [
      'Semnarea acordului de finanțare de 100 mil. EUR cu Banca Europeană de Investiții',
      'Extinderea portofoliului de creditare verde pentru companii',
    ],
    businessModel: 'Bancă universală oferind servicii de retail, corporate banking și investment banking.',
    risks: ['Rata dobânzilor de referință', 'Costul de risc pe segmentul IMM'],
    opportunities: ['Consolidarea cota de piață prin fuziunea cu Alpha Bank'],
    timeline: [
      { year: '2007', event: 'Formarea UniCredit Țiriac Bank în România.' },
      { year: '2024', event: 'Anunțarea tranzacției istorice de fuziune cu Alpha Bank România.' },
    ],
    asOf: '2026-08-22',
  },
  {
    id: 'comp-strabag',
    slug: 'strabag-romania',
    symbol: 'STR',
    cui: 'RO 6601004',
    name: 'STRABAG SRL România',
    logo: null,
    coverImage: '/fallbacks/story-construction-strabag.jpg',
    industry: 'Construcții & Infrastructură',
    industrySlug: 'construction',
    headquarters: 'București, Calea Floreasca nr. 169',
    ownership: 'Grupul STRABAG SE (Austria)',
    management: 'Directorat Executiv România',
    ceo: 'Norbert Pralle',
    revenue: '2.15B RON (FY 2025)',
    revenueValue: 2150000000,
    profit: '112M RON (FY 2025)',
    profitValue: 112000000,
    employees: 1850,
    assets: '1.45B RON',
    assetsValue: 1450000000,
    growth: '+18.5% YoY',
    investments: 'Tehnologii de pavare sustenabilă și șantiere digitale',
    acquisitions: 'Contracte mari de autostrăzi și infrastructură feroviară',
    competitors: ['Umb Spedition', 'Webuild', 'Porr Construct', 'Astaldi'],
    recentDevelopments: [
      'Execuția tronsoanelor cheie pe Autostrada Moldovei A7',
      'Finalizarea lucrărilor de modernizare la terminale aeroportuare',
    ],
    businessModel: 'Construcții civile, infrastructură mare de transport și lucrări hidrotehnice.',
    risks: ['Presiunea pe costul materialelor de construcții', 'Deficitul de forță de muncă calificată'],
    opportunities: ['Finanțările masive prin PNRR și Programul Operațional Transport'],
    timeline: [
      { year: '1994', event: 'Intrarea STRABAG pe piața din România.' },
      { year: '2025', event: 'Atingerea recordului de 2.15 miliarde RON cifră de afaceri.' },
    ],
    asOf: '2026-08-22',
  },
];

export const industriesData: IndustryProfile[] = [
  {
    id: 'ind-banking',
    slug: 'banking',
    name: 'Bănci & Servicii Financiare',
    description: 'Sistemul bancar românesc prezintă o rată solidă de solvabilitate (>23%) și o profitabilitate susținută de marjele de dobândă.',
    marketOverview: 'Activele totale ale sectorului bancar au atins 950 miliarde RON, Banca Transilvania consolidându-și poziția de lider.',
    majorCompanies: ['Banca Transilvania', 'BCR', 'BRD', 'UniCredit Bank', 'ING Bank', 'Raiffeisen Bank'],
    marketLeaders: ['Banca Transilvania (Cota de piață >21%)', 'BCR', 'BRD'],
    growthRate: '+11.2% YoY',
    investmentsVolume: '3.2Mld EUR',
    maVolume: '1.4Mld EUR',
    trends: [
      'Digitalizarea accelerată a serviciilor de mobile banking',
      'Consolidarea pieței prin fuziuni și achiziții (UniCredit + Alpha Bank)',
      'Finanțările verzi și creditele ipotecare verzi reglementate',
    ],
    risks: ['Presiunea taxelor speciale pe activele bancare', 'Evoluția ratelor dobânzilor de referință BNR'],
    opportunities: ['Creșterea gradului de intermediere financiară raportat la PIB'],
    developmentsCount: 24,
    coverImage: '/fallbacks/story-banking-finance.jpg',
  },
  {
    id: 'ind-energy',
    slug: 'energy',
    name: 'Energie & Utilități',
    description: 'Sectorul energetic traversează cea mai profundă transformare prin investiții masive în fotovoltaic, eolian și gaze offshore.',
    marketOverview: 'Proiectele strategice Neptun Deep (OMV Petrom & Romgaz) și extinderea centralei nucleare Kozlodui / Cernavodă redefinesc securitatea regională.',
    majorCompanies: ['Hidroelectrica', 'OMV Petrom', 'Romgaz', 'Nuclearelectrica', 'Electrica'],
    marketLeaders: ['Hidroelectrica (Lider hidro)', 'OMV Petrom (Lider integrat oil & gas)', 'Romgaz (Lider gaz natural)'],
    growthRate: '+15.4% YoY',
    investmentsVolume: '8.5Mld EUR',
    maVolume: '2.1Mld EUR',
    trends: [
      'Prosumatorii fotovoltaici și stocarea în baterii industriale',
      'Dezvoltarea proiectului offshore Neptun Deep',
      'Tranziția spre hidrogen verde și capacități eoliene offshore',
    ],
    risks: ['Fluctuațiile cotațiilor internaționale la gaze și energie electrică', 'Schimbări de reglementare tarifară'],
    opportunities: ['România devine cel mai mare producător net de gaz natural din UE'],
    developmentsCount: 38,
    coverImage: '/fallbacks/story-energy-solar.jpg',
  },
  {
    id: 'ind-real-estate',
    slug: 'real-estate',
    name: 'Real Estate & Dezvoltare Imobiliară',
    description: 'Piața imobiliară din România rămâne dinamică, susținută de tranzacțiile de locuințe și dezvoltările office nZEB.',
    marketOverview: 'Conform ANCPI, se înregistrează lunar peste 51.000 de tranzacții la nivel național, București și Cluj fiind polii principali.',
    majorCompanies: ['One United Properties', 'Skanska România', 'Globalworth', 'NEPI Rockcastle', 'Prime Kapital'],
    marketLeaders: ['One United Properties (Rezidențial premium & Office)', 'NEPI Rockcastle (Retail Mall-uri)'],
    growthRate: '+8.9% YoY',
    investmentsVolume: '1.8Mld EUR',
    maVolume: '750M EUR',
    trends: [
      'Certificările verzi LEED Outstanding & BREEAM Excellent',
      'Dezvoltări mixte de regenerare urbană',
      'Cererea crescută pentru spații logistice de clasa A',
    ],
    risks: ['Ritmul de eliberare a autorizațiilor de construire în marile orașe', 'Evoluția indicilor IRCC/ROBOR'],
    opportunities: ['Randamentele imobiliare de 7-8% atrag fonduri instituționale internaționale'],
    developmentsCount: 19,
    coverImage: '/fallbacks/story-construction-strabag.jpg',
  },
  {
    id: 'ind-construction',
    slug: 'construction',
    name: 'Construcții & Infrastructură',
    description: 'Șantierele de autostrăzi, metrou și infrastructură feroviară înregistrează ritmuri record de execuție finanțate prin PNRR.',
    marketOverview: 'Valoarea totală a lucrărilor de construcții din România depășește 40 miliarde RON anual.',
    majorCompanies: ['STRABAG', 'Umb Spedition', 'Webuild', 'CNAIR', 'CNCF CFR'],
    marketLeaders: ['STRABAG', 'Umb Spedition'],
    growthRate: '+21.2% YoY',
    investmentsVolume: '6.4Mld EUR',
    maVolume: '320M EUR',
    trends: ['Șantierele de metrou Magistrala 6 Otopeni', 'Modernizarea tronsoanelor feroviare trans-europene'],
    risks: ['Presiunea pe costul asfaltenilor și oțelului beton'],
    opportunities: ['Fondurile nerambursabile din PNRR și Programul Transport 2021-2027'],
    developmentsCount: 31,
    coverImage: '/fallbacks/story-construction-strabag.jpg',
  },
  {
    id: 'ind-technology',
    slug: 'technology',
    name: 'Tehnologie, AI & Digital',
    description: 'Ecosistemul tehnologic din România atrage investiții în centre de date, startup-uri AI și securitate cibernetică.',
    marketOverview: 'Sectorul IT&C contribuie cu peste 7% la PIB-ul național, fiind un motor principal al exporturilor de servicii.',
    majorCompanies: ['UiPath', 'Bitdefender', 'Hi Digital', 'Datansify', 'Microsoft România'],
    marketLeaders: ['UiPath (Automation)', 'Bitdefender (Cybersecurity)'],
    growthRate: '+19.6% YoY',
    investmentsVolume: '1.2Mld EUR',
    maVolume: '890M EUR',
    trends: ['Investiția de 380MW în Centre de Date în România', 'Startup-uri AI cu runde de finanțare globale'],
    risks: ['Deficitul de personal tehnic foarte specializat'],
    opportunities: ['Automatizarea proceselor de afaceri prin modele AI generative'],
    developmentsCount: 27,
    coverImage: '/fallbacks/story-apple-tech-cia.jpg',
  },
];

export const dealsData: DealItem[] = [
  {
    id: 'deal-unicredit-bei',
    slug: 'unicredit-bank-romania-finantare-bei-100m-euro',
    company: 'UniCredit Bank România',
    counterparty: 'Banca Europeană de Investiții (BEI)',
    dealType: 'Funding',
    value: '100.000.000 EUR',
    sector: 'Banking & Finanțare IMM',
    date: '2026-08-20',
    status: 'Completed',
    description: 'Linie de creditare facilitată de BEI pentru susținerea investițiilor productive și tranziției verzi în sectorul IMM din România.',
    source: 'Comunicat Oficial BEI & UniCredit',
    coverImage: '/fallbacks/story-banking-finance.jpg',
  },
  {
    id: 'deal-data-center-belgia',
    slug: 'investitie-centre-de-date-380mw-belgia-romania',
    company: 'Consorțiu Investitori Belgia',
    counterparty: 'Autorități Locale & Rețea Energetică',
    dealType: 'Investment',
    value: 'Undisclosed (Est. >300M EUR)',
    sector: 'Tehnologie & Energie',
    date: '2026-08-18',
    status: 'Announced',
    description: 'Una dintre cele mai bogate familii din Belgia plănuiește dezvoltarea de centre de date de nivel industrial de 380MW în România.',
    source: 'Economedia & Raport Investiții',
    coverImage: '/fallbacks/story-energy-solar.jpg',
  },
  {
    id: 'deal-zuckerberg-castle',
    slug: 'achizitie-castel-gotic-zuckerberg',
    company: 'Mark Zuckerberg Family Office',
    counterparty: 'Proprietar Privat',
    dealType: 'Acquisition',
    value: '30.000.000 EUR',
    sector: 'Real Estate & Patrimoniu',
    date: '2026-08-15',
    status: 'Completed',
    description: 'Tranzacție imobiliară istorică pentru un castel gotic din secolul al XIX-lea achiziționat pe piața internațională de patrimoniu.',
    source: 'Raport Imobiliar',
    coverImage: '/fallbacks/story-gothic-castle.jpg',
  },
  {
    id: 'deal-ai-startup-funding',
    slug: 'finantare-1-miliard-dolari-startup-ai',
    company: 'Startup AI Fondat în Regiune',
    counterparty: 'Fonduri Internaționale Venture Capital',
    dealType: 'Venture Capital',
    value: '1.000.000.000 USD',
    sector: 'Artificial Intelligence',
    date: '2026-08-10',
    status: 'Completed',
    description: 'Rundă mega de finanțare atinsă pentru dezvoltarea modelelor LLM și infrastructurii de automatizare AI.',
    source: 'TechCrunch & AiX Intelligence',
    coverImage: '/fallbacks/story-ai-startup.jpg',
  },
];

export const executivesData: ExecutiveProfile[] = [
  {
    id: 'exec-omer-tetik',
    slug: 'omer-tetik',
    name: 'Ömer Tetik',
    currentRole: 'Chief Executive Officer (CEO)',
    company: 'Banca Transilvania',
    companySlug: 'banca-transilvania',
    avatar: '/fallbacks/fallback-1.jpg',
    background: 'Finanțist cu peste 25 de ani de experiență bancară pe piețele din România și Europa Centrală și de Est.',
    previousRoles: ['President Credit Europe Bank România', 'VP Treasury'],
    associatedCompanies: ['Banca Transilvania', 'Bancpost', 'Idea Bank'],
    investments: ['Digitalizare bancară', 'Integration M&A bancar'],
    recentDevelopments: ['Conducerea achiziției și integrării OTP Bank România în cadrul grupului Banca Transilvania.'],
    quote: 'Performanța sustenabilă a băncii noastre derivă direct din susținerea antreprenorilor români și din disciplina de capital.',
  },
  {
    id: 'exec-karoly-borbely',
    slug: 'karoly-borbely',
    name: 'Karoly Borbely',
    currentRole: 'Director General & Președinte Directorat',
    company: 'Hidroelectrica',
    companySlug: 'hidroelectrica',
    avatar: '/fallbacks/fallback-2.jpg',
    background: 'Executive senior specializat pe guvernanță corporativă, strategie energetică și piețe de capital.',
    previousRoles: ['Membru Directorat Hidroelectrica', 'Secretar de Stat Departamentul pentru Energie'],
    associatedCompanies: ['Hidroelectrica', 'Ministerul Energiei'],
    investments: ['Modernizare hidrocentrale', 'Parcuri fotovoltaice și eoliene'],
    recentDevelopments: ['Gestionarea programului de investiții post-listare BVB și optimizarea producției hidro.'],
    quote: 'Hidroelectrica este pilonul verde al independenței energetice a României.',
  },
  {
    id: 'exec-christina-verchere',
    slug: 'christina-verchere',
    name: 'Christina Verchere',
    currentRole: 'Chief Executive Officer (CEO)',
    company: 'OMV Petrom',
    companySlug: 'omv-petrom',
    avatar: '/fallbacks/fallback-3.jpg',
    background: 'Executiv internațional din industria energetică cu carieră de peste 20 de ani la BP și OMV Petrom.',
    previousRoles: ['Regional President BP Canada', 'President BP Indonesia'],
    associatedCompanies: ['OMV Petrom', 'BP plc'],
    investments: ['Proiectul Neptun Deep', 'Energie solară și rețea stații EV'],
    recentDevelopments: ['Coordonarea lucrărilor offshore pentru Neptun Deep în Marea Neagră.'],
    quote: 'Neptun Deep este un proiect transformațional pentru România și pentru securitatea energetică europeană.',
  },
  {
    id: 'exec-radu-burnete',
    slug: 'radu-burnete',
    name: 'Radu Burnete',
    currentRole: 'Director Executiv',
    company: 'Federația Patronală Concordia',
    avatar: '/fallbacks/fallback-4.jpg',
    background: 'Lider patronal și expert în politici economice și dialog social reprezentând marile companii din România.',
    previousRoles: ['Policy Advisor', 'Director Relații Publice'],
    associatedCompanies: ['Concordia', 'AmCham România'],
    investments: ['Cercetare de politici economice și consultare bugetară'],
    recentDevelopments: ['Analiză și dialog pe proiectul Legii Salarizării și reforma fiscală 2026.'],
    quote: 'Predictibilitatea fiscală este condiția esențială pentru menținerea investițiilor mari în economie.',
  },
];

export const radarData: RadarItem[] = [
  {
    id: 'radar-1',
    tag: 'WATCH',
    title: 'Decizia Instanței privind STB & Insolvența',
    entity: 'Societatea de Transport București (STB)',
    sector: 'Transport Public & Finanțe Publice',
    date: '2026-08-21',
    summary: 'Instanța a respins cererea de insolvență a STB. Primăria Capitalei și primarul Ciucu invocă planul de eșalonare a datoriilor.',
    impact: 'Evoluție critică pentru bugetul Capitalei și furnizorii de servicii de transport.',
    slug: 'motivul-pentru-care-instanta-a-respins-intrarea-stb-in-insolventa',
  },
  {
    id: 'radar-2',
    tag: 'INVESTING',
    title: 'Finanțare 100M EUR BEI acordată UniCredit Bank',
    entity: 'UniCredit Bank & BEI',
    sector: 'Banking & Finanțare IMM',
    date: '2026-08-20',
    summary: 'Grupul bancar atrage 100 milioane de euro de la BEI pentru finanțarea proiectelor de dezvoltare și credite verzi destinate IMM-urilor.',
    impact: 'Stimulează accesul la capital ieftin pentru firmele românești în expansiune.',
    slug: 'unicredit-bank-romania-obtine-o-finantare-de-100-milioane-de-euro-de-la-bei-pentru-imm-uri',
  },
  {
    id: 'radar-3',
    tag: 'EXPANDING',
    title: 'Inspecție Japoneză pe Șantierul Metroului Magistrala 6',
    entity: 'Finanțatorii Japonezi & Metrorex',
    sector: 'Infrastructură & Construcții',
    date: '2026-08-19',
    summary: 'Delegația de finanțatori japonezi a inspectat stadiul lucrărilor la Magistrala 6 Otopeni.',
    impact: 'Garantați pe calendarul de livrare al conexiunii de metrou cu Aeroportul Otopeni.',
    slug: 'foto-124-finantatorii-japonezi-ai-magistralei-6-au-venit-in-inspectie-pe-santierele-metrou',
  },
  {
    id: 'radar-4',
    tag: 'GROWING',
    title: 'Finanțare de peste 1 Mld $ Atrași de Startup AI',
    entity: 'Ecosistemul Tech Regional',
    sector: 'AI & Venture Capital',
    date: '2026-08-18',
    summary: 'Un fondator din regiune a atras peste 1 miliard de dolari capital de risc pentru extinderea infrastructurii de AI.',
    impact: 'Validează potențialul global al fondatorilor tech din Europa de Est.',
    slug: 'un-albanez-a-atras-finantari-de-peste-1-miliard-dolari-pentru-startup-ul-sau-ai',
  },
  {
    id: 'radar-5',
    tag: 'DISTRESSED',
    title: 'Legea Salarizării și Presiunea pe Bugetul de Stat',
    entity: 'Guvernul României & Mediul de Afaceri',
    sector: 'Fiscalitate & Piața Muncii',
    date: '2026-08-17',
    summary: 'Discuțiile privind noua variantă a Legii Salarizării vizează recalculări generale și optimizări ale cheltuielilor bugetare.',
    impact: 'Repercursiuni directe asupra muncii și impozitării salariale.',
    slug: 'breaking-documente-124-ce-prevede-noua-varianta-a-legii-salarizarii-din-sectorul-bugetar-p',
  },
];

export const metricsData: BusinessMetricItem[] = [
  {
    id: 'm-1',
    label: 'Companii Active Înregistrate',
    current: '1.140.000',
    previous: '1.095.000',
    yoy: '+4.1%',
    trend: 'up',
    category: 'Macro',
    unit: 'Companii',
    source: 'ONRC',
    updatedAt: '2026-08-20',
  },
  {
    id: 'm-2',
    label: 'Capitalizare Bursa BVB',
    current: '342.5 Mld',
    previous: '304.6 Mld',
    yoy: '+12.4%',
    trend: 'up',
    category: 'BVB',
    unit: 'RON',
    source: 'BVB',
    updatedAt: '2026-08-21',
  },
  {
    id: 'm-3',
    label: 'Tranzacții Imobiliare Lunare',
    current: '51.808',
    previous: '49.710',
    yoy: '+4.2%',
    trend: 'up',
    category: 'Real Estate',
    unit: 'Tranzacții',
    source: 'ANCPI',
    updatedAt: '2026-08-18',
  },
  {
    id: 'm-4',
    label: 'Rată Dobândă Cheie BNR',
    current: '6.50%',
    previous: '6.50%',
    yoy: '0.0%',
    trend: 'neutral',
    category: 'Banking',
    unit: '%',
    source: 'BNR',
    updatedAt: '2026-08-08',
  },
  {
    id: 'm-5',
    label: 'Indice ROBOR 3M',
    current: '5.58%',
    previous: '6.00%',
    yoy: '-0.42%',
    trend: 'down',
    category: 'Banking',
    unit: '%',
    source: 'BNR',
    updatedAt: '2026-08-21',
  },
  {
    id: 'm-6',
    label: 'Volum Volum Tranzacții M&A (YTD)',
    current: '2.85 Mld',
    previous: '2.40 Mld',
    yoy: '+18.7%',
    trend: 'up',
    category: 'Investment',
    unit: 'EUR',
    source: 'AiX Research',
    updatedAt: '2026-08-20',
  },
];

export const insightsData: BusinessInsightItem[] = [
  {
    id: 'ins-1',
    slug: 'analiza-structura-capital-banca-transilvania-hidroelectrica',
    title: 'Modelul de Guvernanță și Structura de Capital la Campionii Economici BVB',
    excerpt: 'Cum reușesc marile corporații din România să mențină rate înalte de distribuție a dividendelor în timp ce finanțează planuri masive de capeks.',
    category: 'Corporate Strategy',
    authorName: 'Redacția Economică AiX Media',
    publishedAt: '2026-08-19',
    readTime: '6 min read',
    coverImage: '/fallbacks/story-banking-finance.jpg',
    whyItMatters: [
      'Banca Transilvania și Hidroelectrica reprezintă peste 35% din indicele BET.',
      'Alocarea eficientă a capitalului este decisivă pentru randamentele fondurilor Pilon II.',
    ],
  },
  {
    id: 'ins-2',
    slug: 'tranzitia-energetica-si-gazul-din-marea-neagra-neptun-deep',
    title: 'Neptun Deep și Securitatea Energetică Regională: De la Proiect la Producție',
    excerpt: 'Impactul celor peste 100 miliarde metri cubi de gaz estimat în Marea Neagră asupra balanței comerciale a României.',
    category: 'Energy & Infrastructure',
    authorName: 'Cristian Văduva',
    publishedAt: '2026-08-15',
    readTime: '8 min read',
    coverImage: '/fallbacks/story-energy-solar.jpg',
    whyItMatters: [
      'România devine cel mai mare producător independent de gaz natural din Uniunea Europeană.',
      'Veniturile din redevențe pot finanța proiecte majore de infrastructură.',
    ],
  },
];
