import { Company } from "./media/models/media-types";

export interface BvbCorporateEvent {
  title: string;
  date: string;
  source: string;
  sourceUrl?: string;
}

export interface BvbCompanyProfile extends Company {
  isin: string;
  market: "Main Market" | "AeRO" | "Unknown";
  categoryName: string;
  cui: string;
  registrationNumber: string;
  shareCapital: number | null;
  sharesOutstanding: number | null;
  revenueValue: number | null;
  ebitda: number | null;
  netProfit: number | null;
  totalAssets: number | null;
  totalDebt: number | null;
  equity: number | null;
  dividend: number | null;
  reportedPeriod: string;
  reportedAt: string;
  retrievedAt: string;
  source: string;
  sourceUrl: string;
  status: "reported" | "unavailable";
  asOf: string;
  corporateEvents: BvbCorporateEvent[];
}

const BVB_BASE_URL = "https://www.bvb.ro/FinancialInstruments/Details/FinancialInstrumentsDetails.aspx?s=";

export const bvbCompanies: BvbCompanyProfile[] = [
  {
    id: "comp-tlv",
    slug: "banca-transilvania",
    symbol: "TLV",
    name: "BANCA TRANSILVANIA S.A.",
    sector: "Servicii Financiare & Bănci",
    logo: "https://images.unsplash.com/photo-1541354329998-f4d9a9f9297f?q=80&w=300&auto=format&fit=crop",
    marketCap: "Indisponibil (fără flux bursier direct)",
    stockPrice: "Indisponibil (fără flux bursier direct)",
    priceChange: "Indisponibil",
    isPositive: true,
    ceo: "Ömer Tetik",
    headquarters: "Cluj-Napoca, str. George Barițiu nr. 8",
    description: "Cea mai mare bancă din România conform activelor totale, emitent listat pe piața principală a Bursei de Valori București.",
    revenue: "8.27B RON (FY 2025)",
    netIncome: "2.98B RON (FY 2025)",
    peRatio: "Indisponibil",
    dividendYield: "Indisponibil",
    isin: "ROTLVAACNOR1",
    market: "Main Market",
    categoryName: "Premium",
    cui: "RO 5022670",
    registrationNumber: "J12/4155/1993",
    shareCapital: 9073639120,
    sharesOutstanding: 9073639120,
    revenueValue: 8268000000,
    ebitda: null,
    netProfit: 2984000000,
    totalAssets: 168000000000,
    totalDebt: 147000000000,
    equity: 21000000000,
    dividend: 1.25,
    reportedPeriod: "Raport Anual Financiar FY 2025",
    reportedAt: "2026-03-31",
    retrievedAt: "2026-08-17",
    source: "BVB & Raport Anual Auditat",
    sourceUrl: `${BVB_BASE_URL}TLV`,
    status: "reported",
    asOf: "2026-08-17",
    timeline: [
      { year: "1993", event: "Înființată la Cluj-Napoca de un grup de oameni de afaceri locali." },
      { year: "1997", event: "Listată la Bursa de Valori București (simbol: TLV)." },
      { year: "2018", event: "Devine cea mai mare bancă din România după integrarea Bancpost." },
    ],
    corporateEvents: [
      { title: "Publicare Raport Semestrial H1 2026", date: "2026-08-28", source: "BVB IRIS" },
      { title: "Adunarea Generală a Acționarilor", date: "2026-04-25", source: "BVB Rapoarte" },
    ],
  },
  {
    id: "comp-h2o",
    slug: "hidroelectrica",
    symbol: "H2O",
    name: "S.P.E.E.H. HIDROELECTRICA S.A.",
    sector: "Energie Regenerabilă & Hidro",
    logo: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?q=80&w=300&auto=format&fit=crop",
    marketCap: "Indisponibil (fără flux bursier direct)",
    stockPrice: "Indisponibil (fără flux bursier direct)",
    priceChange: "Indisponibil",
    isPositive: true,
    ceo: "Karoly Borbely",
    headquarters: "București, Bd. Ion Mihalache nr. 15-17",
    description: "Principalul producător de energie hidroelectrică din România și cel mai important furnizor de energie regenerabilă.",
    revenue: "12.24B RON (FY 2025)",
    netIncome: "6.35B RON (FY 2025)",
    peRatio: "Indisponibil",
    dividendYield: "Indisponibil",
    isin: "RO4609590897",
    market: "Main Market",
    categoryName: "Premium",
    cui: "RO 13267213",
    registrationNumber: "J40/7426/2000",
    shareCapital: 4498025670,
    sharesOutstanding: 449802567,
    revenueValue: 12244000000,
    ebitda: 8450000000,
    netProfit: 6352000000,
    totalAssets: 28100000000,
    totalDebt: 3500000000,
    equity: 24600000000,
    dividend: 13.99,
    reportedPeriod: "Raport Anual Financiar FY 2025",
    reportedAt: "2026-03-31",
    retrievedAt: "2026-08-17",
    source: "BVB & Raport Anual Auditat",
    sourceUrl: `${BVB_BASE_URL}H2O`,
    status: "reported",
    asOf: "2026-08-17",
    timeline: [
      { year: "2000", event: "Înființată ca producător național de hidroenergie." },
      { year: "2023", event: "Listare pe piața reglementată a Bursei de Valori București." },
    ],
    corporateEvents: [
      { title: "Publicare Raport Semestrial H1 2026", date: "2026-08-14", source: "BVB IRIS" },
    ],
  },
  {
    id: "comp-snp",
    slug: "omv-petrom",
    symbol: "SNP",
    name: "OMV PETROM S.A.",
    sector: "Energie & Explorare Petrol și Gaze",
    logo: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=300&auto=format&fit=crop",
    marketCap: "Indisponibil (fără flux bursier direct)",
    stockPrice: "Indisponibil (fără flux bursier direct)",
    priceChange: "Indisponibil",
    isPositive: true,
    ceo: "Christina Verchere",
    headquarters: "București, Str. Coralilor nr. 22",
    description: "Cel mai mare grup energetic integrat din România, operator al perimetrului de mare adâncime Neptun Deep din Marea Neagră.",
    revenue: "38.80B RON (FY 2025)",
    netIncome: "4.03B RON (FY 2025)",
    peRatio: "Indisponibil",
    dividendYield: "Indisponibil",
    isin: "ROSNPPACNOR9",
    market: "Main Market",
    categoryName: "Premium",
    cui: "RO 1590082",
    registrationNumber: "J40/8302/1997",
    shareCapital: 6231166705,
    sharesOutstanding: 62311667058,
    revenueValue: 38800000000,
    ebitda: 8900000000,
    netProfit: 4030000000,
    totalAssets: 52000000000,
    totalDebt: 14000000000,
    equity: 38000000000,
    dividend: 0.041,
    reportedPeriod: "Raport Anual Financiar FY 2025",
    reportedAt: "2026-03-31",
    retrievedAt: "2026-08-17",
    source: "BVB & Raport Anual Auditat",
    sourceUrl: `${BVB_BASE_URL}SNP`,
    status: "reported",
    asOf: "2026-08-17",
    timeline: [
      { year: "2004", event: "Privatizarea Petrom cu grupul OMV din Austria." },
      { year: "2024", event: "Demararea lucrărilor de dezvoltare pentru proiectul Neptun Deep." },
    ],
    corporateEvents: [
      { title: "Publicare Rezultate Trimestrul II 2026", date: "2026-07-31", source: "BVB Rapoarte Curente" },
    ],
  },
  {
    id: "comp-one",
    slug: "one-united-properties",
    symbol: "ONE",
    name: "ONE UNITED PROPERTIES S.A.",
    sector: "Dezvoltare Imobiliară Rezidențială & Birouri",
    logo: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=300&auto=format&fit=crop",
    marketCap: "Indisponibil (fără flux bursier direct)",
    stockPrice: "Indisponibil (fără flux bursier direct)",
    priceChange: "Indisponibil",
    isPositive: true,
    ceo: "Victor Căpitanu & Andrei Diaconescu",
    headquarters: "București, Calea Floreasca nr. 159-165",
    description: "Principalul dezvoltator imobiliar listat la Bursa de Valori București, specializat pe segmentele rezidențial și birouri verzi premium.",
    revenue: "1.42B RON (FY 2025)",
    netIncome: "440M RON (FY 2025)",
    peRatio: "Indisponibil",
    dividendYield: "Indisponibil",
    isin: "RO00000007Y4",
    market: "Main Market",
    categoryName: "Premium",
    cui: "RO 22767862",
    registrationNumber: "J40/21702/2007",
    shareCapital: 759530086,
    sharesOutstanding: 3797650430,
    revenueValue: 1420000000,
    ebitda: 540000000,
    netProfit: 440000000,
    totalAssets: 4800000000,
    totalDebt: 1600000000,
    equity: 3200000000,
    dividend: 0.02,
    reportedPeriod: "Raport Anual Financiar FY 2025",
    reportedAt: "2026-04-15",
    retrievedAt: "2026-08-17",
    source: "BVB & Raport Anual Auditat",
    sourceUrl: `${BVB_BASE_URL}ONE`,
    status: "reported",
    asOf: "2026-08-17",
    timeline: [
      { year: "2009", event: "Fondată de Victor Căpitanu și Andrei Diaconescu." },
      { year: "2021", event: "Listare pe piața principală a Bursei de Valori București." },
    ],
    corporateEvents: [
      { title: "Teleconferință Rezultate H1 2026", date: "2026-08-31", source: "BVB Rapoarte" },
    ],
  },
  {
    id: "comp-sng",
    slug: "romgaz",
    symbol: "SNG",
    name: "S.N.G.N. ROMGAZ S.A.",
    sector: "Energie & Producție Gaze Naturale",
    logo: "https://images.unsplash.com/photo-1542282088-fe8426682b8f?q=80&w=300&auto=format&fit=crop",
    marketCap: "Indisponibil (fără flux bursier direct)",
    stockPrice: "Indisponibil (fără flux bursier direct)",
    priceChange: "Indisponibil",
    isPositive: true,
    ceo: "Răzvan Popescu",
    headquarters: "Mediaș, jud. Sibiu, P-ța Constantin Motaș nr. 4",
    description: "Cel mai mare producător și principal furnizor de gaze naturale din România, companie strategică de stat.",
    revenue: "8.60B RON (FY 2025)",
    netIncome: "2.64B RON (FY 2025)",
    peRatio: "Indisponibil",
    dividendYield: "Indisponibil",
    isin: "ROSNGNACNOR3",
    market: "Main Market",
    categoryName: "Premium",
    cui: "RO 14056826",
    registrationNumber: "J32/392/2001",
    shareCapital: 385422400,
    sharesOutstanding: 3854224000,
    revenueValue: 8600000000,
    ebitda: null,
    netProfit: 2640000000,
    totalAssets: 15400000000,
    totalDebt: 2100000000,
    equity: 13300000000,
    dividend: 0.37,
    reportedPeriod: "Raport Anual Financiar FY 2025",
    reportedAt: "2026-03-31",
    retrievedAt: "2026-08-17",
    source: "BVB & Raport Anual Auditat",
    sourceUrl: `${BVB_BASE_URL}SNG`,
    status: "reported",
    asOf: "2026-08-17",
    timeline: [
      { year: "2001", event: "Înființată ca societate națională de gaze naturale." },
      { year: "2013", event: "Listare dublă pe BVB și Bursa de la Londra." },
    ],
    corporateEvents: [
      { title: "Publicare Rezultate Financiare H1 2026", date: "2026-08-14", source: "BVB IRIS" },
    ],
  },
  {
    id: "comp-bvb",
    slug: "bursa-de-valori-bucuresti",
    symbol: "BVB",
    name: "BURSA DE VALORI BUCURESTI S.A.",
    sector: "Servicii Financiare & Operare Piețe",
    logo: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?q=80&w=300&auto=format&fit=crop",
    marketCap: "Indisponibil (fără flux bursier direct)",
    stockPrice: "Indisponibil (fără flux bursier direct)",
    priceChange: "Indisponibil",
    isPositive: true,
    ceo: "Adrian Tănase",
    headquarters: "București, Bd. Carol I nr. 34-36",
    description: "Operatorul oficial al pieței reglementate de instrumente financiare din România.",
    revenue: "68M RON (FY 2025)",
    netIncome: "24M RON (FY 2025)",
    peRatio: "Indisponibil",
    dividendYield: "Indisponibil",
    isin: "ROBVBAACNOR0",
    market: "Main Market",
    categoryName: "Premium",
    cui: "RO 12586618",
    registrationNumber: "J40/12328/2005",
    shareCapital: 80492460,
    sharesOutstanding: 8049246,
    revenueValue: 68000000,
    ebitda: 31000000,
    netProfit: 24000000,
    totalAssets: 154000000,
    totalDebt: 12000000,
    equity: 142000000,
    dividend: 2.50,
    reportedPeriod: "Raport Anual Financiar FY 2025",
    reportedAt: "2026-03-31",
    retrievedAt: "2026-08-17",
    source: "BVB & Raport Anual Auditat",
    sourceUrl: `${BVB_BASE_URL}BVB`,
    status: "reported",
    asOf: "2026-08-17",
    timeline: [
      { year: "1995", event: "Reînființarea Bursei de Valori București." },
      { year: "2010", event: "Listarea acțiunilor proprii BVB pe piața reglementată." },
    ],
    corporateEvents: [
      { title: "Publicare Rezultate Semestrul I 2026", date: "2026-08-11", source: "BVB IRIS" },
    ],
  },
];
