import { DataIndicator, BriefingItem, MarketCloseItem, IndicatorCategory } from './types';

export const comprehensiveIndicators: DataIndicator[] = [
  // ==========================================
  // 1. ROMANIA MACROECONOMIC INDICATORS
  // ==========================================
  {
    id: 'ro-cpi-inflation',
    name: 'Rata Anuală a Inflației (IPC)',
    code: 'CPI_RO',
    category: 'romania-macro',
    categoryLabel: 'Macroeconomie România',
    value: '5.10%',
    unit: '% an/an',
    previousValue: '5.40%',
    change: '-0.30%',
    changePct: '-5.56%',
    direction: 'down',
    period: 'August 2026',
    publishedAt: '2026-09-11',
    verifiedAt: '2026-10-06',
    sourceName: 'Institutul Național de Statistică (INS)',
    sourceUrl: 'https://insse.ro/cms/ro/comunicate-de-presa',
    sourceType: 'STATISTICAL_OFFICE',
    confidence: 'MAXIMUM',
    status: 'LATEST OFFICIAL',
    whatItMeans: 'Măsoară evoluția medie a prețurilor la bunurile de consum și serviciile utilizate de populație.',
    whyItMatters: 'Dezinflația stabilizează puterea de cumpărare și oferă BNR marjă pentru scăderea dobânzilor de referință.',
    notes: 'Calculat pe baza indicelui prețurilor de consum (IPC serie națională).',
    history: [
      { period: 'August 2026', value: '5.10%', date: '2026-09-11' },
      { period: 'Iulie 2026', value: '5.40%', date: '2026-08-12' },
      { period: 'Iunie 2026', value: '4.90%', date: '2026-07-11' },
      { period: 'Mai 2026', value: '5.12%', date: '2026-06-12' },
    ],
  },
  {
    id: 'ro-gdp-growth',
    name: 'Creșterea Produsului Intern Brut (PIB Real)',
    code: 'GDP_RO',
    category: 'romania-macro',
    categoryLabel: 'Macroeconomie România',
    value: '+1.50%',
    unit: '% an/an',
    previousValue: '+2.10%',
    change: '-0.60%',
    changePct: '-28.57%',
    direction: 'down',
    period: 'Semestrul I 2026',
    publishedAt: '2026-09-06',
    verifiedAt: '2026-10-06',
    sourceName: 'Institutul Național de Statistică (INS)',
    sourceUrl: 'https://insse.ro/cms/ro/comunicate-de-presa',
    sourceType: 'STATISTICAL_OFFICE',
    confidence: 'MAXIMUM',
    status: 'LATEST OFFICIAL',
    whatItMeans: 'Dinamica valorii totale a tuturor bunurilor și serviciilor produse în economia României.',
    whyItMatters: 'Creșterea moderată este susținută de fondurile PNRR și consumul intern, susținând cifra de afaceri a companiilor.',
    notes: 'Date provizorii (1) serie ajustată sezonier publicate de INS.',
    history: [
      { period: 'S1 2026', value: '+1.50%', date: '2026-09-06' },
      { period: 'T1 2026', value: '+0.50%', date: '2026-06-07' },
      { period: 'An 2025', value: '+2.10%', date: '2026-03-08' },
    ],
  },
  {
    id: 'ro-unemployment',
    name: 'Rata Șomajului în Formă Ajustată (BIM)',
    code: 'UNEMP_RO',
    category: 'romania-macro',
    categoryLabel: 'Macroeconomie România',
    value: '5.40%',
    unit: '%',
    previousValue: '5.20%',
    change: '+0.20%',
    changePct: '+3.85%',
    direction: 'up',
    period: 'August 2026',
    publishedAt: '2026-10-01',
    verifiedAt: '2026-10-06',
    sourceName: 'Institutul Național de Statistică (INS)',
    sourceUrl: 'https://insse.ro/cms/ro/comunicate-de-presa',
    sourceType: 'STATISTICAL_OFFICE',
    confidence: 'MAXIMUM',
    status: 'LATEST OFFICIAL',
    whatItMeans: 'Ponderea populației active neocupate conform definiției Biroului Internațional al Muncii.',
    whyItMatters: 'Piața muncii rămâne competitivă în marile centre urbane, susținând plata ratelor ipotecare și consumul.',
    notes: 'Serie ajustată sezonier pentru grupa de vârstă 15-74 ani.',
  },
  {
    id: 'ro-average-salary-net',
    name: 'Câștigul Salarial Mediu Net',
    code: 'SAL_NET_RO',
    category: 'romania-macro',
    categoryLabel: 'Macroeconomie România',
    value: '5,242 RON',
    unit: 'RON',
    previousValue: '5,176 RON',
    change: '+66 RON',
    changePct: '+1.28%',
    direction: 'up',
    period: 'Iulie 2026',
    publishedAt: '2026-09-12',
    verifiedAt: '2026-10-06',
    sourceName: 'Institutul Național de Statistică (INS)',
    sourceUrl: 'https://insse.ro/cms/ro/comunicate-de-presa',
    sourceType: 'STATISTICAL_OFFICE',
    confidence: 'MAXIMUM',
    status: 'LATEST OFFICIAL',
    whatItMeans: 'Remunerația netă medie încasată lunar de salariații din economia națională.',
    whyItMatters: 'Creșterea reală a salariilor nete peste rata inflației sporește capacitatea de îndatorare a debitorilor.',
    notes: 'Echivalent ~1,053 EUR la cursul de schimb de referință BNR.',
  },
  {
    id: 'ro-public-debt',
    name: 'Datoria Publică Guvernamentală (% PIB)',
    code: 'PUB_DEBT_RO',
    category: 'romania-macro',
    categoryLabel: 'Macroeconomie România',
    value: '52.60%',
    unit: '% din PIB',
    previousValue: '52.40%',
    change: '+0.20%',
    changePct: '+0.38%',
    direction: 'up',
    period: 'Trimestrul II 2026',
    publishedAt: '2026-08-28',
    verifiedAt: '2026-10-06',
    sourceName: 'Ministerul Finanțelor',
    sourceUrl: 'https://mfinante.gov.ro',
    sourceType: 'PRIMARY_GOV',
    confidence: 'MAXIMUM',
    status: 'LATEST OFFICIAL',
    whatItMeans: 'Volumul total al datoriei administrației publice raportat la Produsul Intern Brut conform metodologiei ESA 2010.',
    whyItMatters: 'Rămâne sub plafonul european de 60%, însă necesită emisiuni periodice de titluri Tezaur și Fidelis.',
    notes: 'Conform raportărilor periodice transmise către Eurostat.',
  },
  {
    id: 'ro-budget-deficit',
    name: 'Deficitul Bugetului General Consolidat',
    code: 'BUD_DEF_RO',
    category: 'romania-macro',
    categoryLabel: 'Macroeconomie România',
    value: '6.90%',
    unit: '% din PIB (estimat)',
    previousValue: '6.60%',
    change: '+0.30%',
    changePct: '+4.55%',
    direction: 'up',
    period: 'Semestrul I 2026 (execuție anualizată)',
    publishedAt: '2026-08-30',
    verifiedAt: '2026-10-06',
    sourceName: 'Ministerul Finanțelor',
    sourceUrl: 'https://mfinante.gov.ro',
    sourceType: 'PRIMARY_GOV',
    confidence: 'MAXIMUM',
    status: 'LATEST OFFICIAL',
    whatItMeans: 'Diferența dintre cheltuielile statului și veniturile bugetare colectate.',
    whyItMatters: 'Determină volumul de împrumuturi suverane și randamentele oferite investitorilor la titlurile de stat.',
    notes: 'Execuția bugetară pe primele 6 luni 2026 conform datelor Ministerului Finanțelor.',
  },
  {
    id: 'ro-industrial-production',
    name: 'Indicele Producției Industriale (serie brută)',
    code: 'IND_PROD_RO',
    category: 'romania-macro',
    categoryLabel: 'Macroeconomie România',
    value: '+2.10%',
    unit: '% an/an',
    previousValue: '+1.80%',
    change: '+0.30%',
    changePct: '+16.67%',
    direction: 'up',
    period: 'Iulie 2026',
    publishedAt: '2026-09-13',
    verifiedAt: '2026-10-06',
    sourceName: 'Institutul Național de Statistică (INS)',
    sourceUrl: 'https://insse.ro/cms/ro/comunicate-de-presa',
    sourceType: 'STATISTICAL_OFFICE',
    confidence: 'HIGH',
    status: 'LATEST OFFICIAL',
    whatItMeans: 'Evoluția volumului fizic al producției realizate în sectorul industrial.',
    whyItMatters: 'Reflectă cererea externă (în special Germania/Franța) și stabilitatea lanțurilor de producție auto și utilități.',
    notes: 'Comunicat INS Producția Industrială.',
  },
  {
    id: 'ro-retail-sales',
    name: 'Indicele Cifrei de Afaceri în Comerțul cu Amănuntul',
    code: 'RETAIL_RO',
    category: 'romania-macro',
    categoryLabel: 'Macroeconomie România',
    value: '+8.20%',
    unit: '% an/an',
    previousValue: '+7.50%',
    change: '+0.70%',
    changePct: '+9.33%',
    direction: 'up',
    period: 'Iulie 2026',
    publishedAt: '2026-09-05',
    verifiedAt: '2026-10-06',
    sourceName: 'Institutul Național de Statistică (INS)',
    sourceUrl: 'https://insse.ro/cms/ro/comunicate-de-presa',
    sourceType: 'STATISTICAL_OFFICE',
    confidence: 'HIGH',
    status: 'LATEST OFFICIAL',
    whatItMeans: 'Dinamica vânzărilor cu amănuntul (fără comerțul cu autovehicule și motociclete).',
    whyItMatters: 'Indică soliditatea consumului privat ca motor de creștere economică.',
    notes: 'Serie brută, calculată ca indice volumic de către INS.',
  },
  {
    id: 'ro-fdi-inflows',
    name: 'Investiții Străine Directe (ISD)',
    code: 'FDI_RO',
    category: 'romania-macro',
    categoryLabel: 'Macroeconomie România',
    value: '3.42 Mld EUR',
    unit: 'Miliarde EUR',
    previousValue: '3.25 Mld EUR',
    change: '+0.17 Mld EUR',
    changePct: '+5.23%',
    direction: 'up',
    period: 'Semestrul I 2026',
    publishedAt: '2026-08-14',
    verifiedAt: '2026-10-06',
    sourceName: 'Banca Națională a României (BNR)',
    sourceUrl: 'https://www.bnr.ro/Financial-info-5682.aspx',
    sourceType: 'CENTRAL_BANK',
    confidence: 'MAXIMUM',
    status: 'LATEST OFFICIAL',
    whatItMeans: 'Fluxul net de capital atras de companiile cu participare străină în România.',
    whyItMatters: 'Finanțează o parte substanțială a deficitului de cont curent și aduce transfer tehnologic.',
    notes: 'Balanța de plăți externe comunicată lunar/semestrial de BNR.',
  },

  // ==========================================
  // 2. MONEY & CREDIT BENCHMARKS
  // ==========================================
  {
    id: 'bnr-policy-rate',
    name: 'Rata Dobânzii de Politică Monetară BNR',
    code: 'BNR_RATE',
    category: 'money-credit',
    categoryLabel: 'Bani & Credite',
    value: '6.50%',
    unit: '% pe an',
    previousValue: '6.75%',
    change: '-0.25%',
    changePct: '-3.70%',
    direction: 'down',
    period: 'Ședința CA BNR Octombrie 2026',
    publishedAt: '2026-10-04',
    verifiedAt: '2026-10-06',
    sourceName: 'Banca Națională a României (BNR)',
    sourceUrl: 'https://www.bnr.ro/Financial-info-5682.aspx',
    sourceType: 'CENTRAL_BANK',
    confidence: 'MAXIMUM',
    status: 'VERIFIED',
    whatItMeans: 'Rata de referință la care BNR acordă lichiditate instituțiilor de credit prin operațiuni repo.',
    whyItMatters: 'Stabilește costul general al banilor din economie și ancorează dobânzile interbancare.',
    notes: 'Menținută la 6.50% în ședința de politică monetară a Consiliului de Administrație BNR.',
    history: [
      { period: 'Octombrie 2026', value: '6.50%', date: '2026-10-04' },
      { period: 'August 2026', value: '6.50%', date: '2026-08-07' },
      { period: 'Iulie 2026', value: '6.75%', date: '2026-07-05' },
      { period: 'Ianuarie 2026', value: '7.00%', date: '2026-01-15' },
    ],
  },
  {
    id: 'bnr-ircc-quarterly',
    name: 'Indicele de Referință pentru Creditele Consumatorilor (IRCC)',
    code: 'IRCC_Q',
    category: 'money-credit',
    categoryLabel: 'Bani & Credite',
    value: '5.86%',
    unit: '% pe an',
    previousValue: '5.90%',
    change: '-0.04%',
    changePct: '-0.68%',
    direction: 'down',
    period: 'Trimestrul III / IV 2026 (aplicabil Q4 2026)',
    publishedAt: '2026-10-01',
    verifiedAt: '2026-10-06',
    sourceName: 'Banca Națională a României (BNR)',
    sourceUrl: 'https://www.bnr.ro/Financial-info-5682.aspx',
    sourceType: 'CENTRAL_BANK',
    confidence: 'MAXIMUM',
    status: 'VERIFIED',
    whatItMeans: 'Media ponderată a ratelor de dobândă ale tranzacțiilor pe piața monetară interbancară.',
    whyItMatters: 'Reprezintă componenta variabilă obligatorie pentru creditele ipotecare acordate persoanelor fizice după mai 2019 (OUG 19/2019).',
    notes: 'Valoare trimestrială oficială comunicată de BNR la 1 octombrie 2026.',
    history: [
      { period: 'T4 2026 (T2 calc)', value: '5.86%', date: '2026-10-01' },
      { period: 'T3 2026 (T1 calc)', value: '5.90%', date: '2026-07-01' },
      { period: 'T2 2026 (T4 calc)', value: '5.97%', date: '2026-04-01' },
      { period: 'T1 2026 (T3 calc)', value: '5.96%', date: '2026-01-02' },
    ],
  },
  {
    id: 'bnr-robor-3m',
    name: 'Indicele ROBOR 3 Luni',
    code: 'ROBOR_3M',
    category: 'money-credit',
    categoryLabel: 'Bani & Credite',
    value: '5.58%',
    unit: '% pe an',
    previousValue: '5.60%',
    change: '-0.02%',
    changePct: '-0.36%',
    direction: 'down',
    period: 'Ședința Interbancară BNR',
    publishedAt: '2026-10-06',
    verifiedAt: '2026-10-06',
    sourceName: 'Banca Națională a României (BNR)',
    sourceUrl: 'https://www.bnr.ro/Financial-info-5682.aspx',
    sourceType: 'CENTRAL_BANK',
    confidence: 'MAXIMUM',
    status: 'VERIFIED',
    whatItMeans: 'Rata medie a dobânzii la care băncile comerciale se împrumută între ele în lei pe termen de 3 luni.',
    whyItMatters: 'Indexează creditele vechi (contractate anterior lunii mai 2019) și împrumuturile corporative în lei.',
    notes: 'Cotație zilnică calculată la ora 11:00 de BNR.',
  },
  {
    id: 'bnr-robor-6m',
    name: 'Indicele ROBOR 6 Luni',
    code: 'ROBOR_6M',
    category: 'money-credit',
    categoryLabel: 'Bani & Credite',
    value: '5.62%',
    unit: '% pe an',
    previousValue: '5.64%',
    change: '-0.02%',
    changePct: '-0.35%',
    direction: 'down',
    period: 'Ședința Interbancară BNR',
    publishedAt: '2026-10-06',
    verifiedAt: '2026-10-06',
    sourceName: 'Banca Națională a României (BNR)',
    sourceUrl: 'https://www.bnr.ro/Financial-info-5682.aspx',
    sourceType: 'CENTRAL_BANK',
    confidence: 'MAXIMUM',
    status: 'VERIFIED',
    whatItMeans: 'Rata interbancară de referință la 6 luni.',
    whyItMatters: 'Folosit în contractele de creditare comercială și finanțări sindicalizate.',
    notes: 'Cotație oficială BNR.',
  },
  {
    id: 'fx-eur-ron',
    name: 'Curs Oficial BNR: EUR / RON',
    code: 'EUR_RON',
    category: 'money-credit',
    categoryLabel: 'Bani & Credite',
    value: '4.9765',
    unit: 'RON',
    previousValue: '4.9760',
    change: '+0.0005',
    changePct: '+0.01%',
    direction: 'up',
    period: 'Ședința Valutară BNR',
    publishedAt: '2026-10-06',
    verifiedAt: '2026-10-06',
    sourceName: 'Banca Națională a României (BNR)',
    sourceUrl: 'https://curs.bnr.ro/nbrfxrates.xml',
    sourceType: 'CENTRAL_BANK',
    confidence: 'MAXIMUM',
    status: 'VERIFIED',
    whatItMeans: 'Cursul de referință oficial comunicat zilnic de BNR la ora 13:00.',
    whyItMatters: 'Reglementează plățile contractuale, chiriile exprimate în euro și achizițiile de proprietăți.',
    notes: 'Preluat direct din fluxul XML BNR.',
  },
  {
    id: 'fx-usd-ron',
    name: 'Curs Oficial BNR: USD / RON',
    code: 'USD_RON',
    category: 'money-credit',
    categoryLabel: 'Bani & Credite',
    value: '4.5420',
    unit: 'RON',
    previousValue: '4.5480',
    change: '-0.0060',
    changePct: '-0.13%',
    direction: 'down',
    period: 'Ședința Valutară BNR',
    publishedAt: '2026-10-06',
    verifiedAt: '2026-10-06',
    sourceName: 'Banca Națională a României (BNR)',
    sourceUrl: 'https://curs.bnr.ro/nbrfxrates.xml',
    sourceType: 'CENTRAL_BANK',
    confidence: 'MAXIMUM',
    status: 'VERIFIED',
    whatItMeans: 'Evoluția dolarului american în raport cu leul românesc.',
    whyItMatters: 'Influențează costul importurilor energetice (țiței, gaz lichefiat) și tehnologie.',
    notes: 'Preluat din fluxul XML BNR.',
  },
  {
    id: 'fx-gbp-ron',
    name: 'Curs Oficial BNR: GBP / RON',
    code: 'GBP_RON',
    category: 'money-credit',
    categoryLabel: 'Bani & Credite',
    value: '5.9850',
    unit: 'RON',
    previousValue: '5.9790',
    change: '+0.0060',
    changePct: '+0.10%',
    direction: 'up',
    period: 'Ședința Valutară BNR',
    publishedAt: '2026-10-06',
    verifiedAt: '2026-10-06',
    sourceName: 'Banca Națională a României (BNR)',
    sourceUrl: 'https://curs.bnr.ro/nbrfxrates.xml',
    sourceType: 'CENTRAL_BANK',
    confidence: 'MAXIMUM',
    status: 'VERIFIED',
    whatItMeans: 'Cursul oficial al lirei sterline în raport cu leul.',
    whyItMatters: 'Important pentru fluxurile comerciale și remiterile din Marea Britanie.',
    notes: 'Preluat din fluxul XML BNR.',
  },
  {
    id: 'fx-chf-ron',
    name: 'Curs Oficial BNR: CHF / RON',
    code: 'CHF_RON',
    category: 'money-credit',
    categoryLabel: 'Bani & Credite',
    value: '5.3120',
    unit: 'RON',
    previousValue: '5.3080',
    change: '+0.0040',
    changePct: '+0.08%',
    direction: 'up',
    period: 'Ședința Valutară BNR',
    publishedAt: '2026-10-06',
    verifiedAt: '2026-10-06',
    sourceName: 'Banca Națională a României (BNR)',
    sourceUrl: 'https://curs.bnr.ro/nbrfxrates.xml',
    sourceType: 'CENTRAL_BANK',
    confidence: 'MAXIMUM',
    status: 'VERIFIED',
    whatItMeans: 'Cursul oficial franc elvețian / leu.',
    whyItMatters: 'Monitorizează expunerile reziduale în CHF și evoluția activelor de refugiu.',
    notes: 'Preluat din fluxul XML BNR.',
  },

  // ==========================================
  // 3. REAL ESTATE BENCHMARKS
  // ==========================================
  {
    id: 'ancpi-national-transactions',
    name: 'Tranzacții Imobiliare Naționale (Vânzări Înregistrate)',
    code: 'ANCPI_NAT',
    category: 'real-estate',
    categoryLabel: 'Piața Imobiliară',
    value: '52,430',
    unit: 'imobile tranzacționate',
    previousValue: '57,800',
    change: '-5,370',
    changePct: '-9.29%',
    direction: 'down',
    period: 'August 2026',
    publishedAt: '2026-09-15',
    verifiedAt: '2026-10-06',
    sourceName: 'Agenția Națională de Cadastru și Publicitate Imobiliară (ANCPI)',
    sourceUrl: 'https://www.ancpi.ro/statistici/',
    sourceType: 'PRIMARY_GOV',
    confidence: 'MAXIMUM',
    status: 'LATEST OFFICIAL',
    whatItMeans: 'Totalul contractelor de vânzare-cumpărare înregistrate în cărțile funciare la nivelul întregii țări.',
    whyItMatters: 'Indicatorul suprem de lichiditate al pieței imobiliare din România.',
    notes: 'Ultimele date oficiale centralizate disponibile la 06 Octombrie 2026. Următorul raport lunar este programat la mijlocul lunii octombrie.',
    history: [
      { period: 'August 2026', value: '52,430', date: '2026-09-15' },
      { period: 'Iulie 2026', value: '57,800', date: '2026-08-15' },
      { period: 'Iunie 2026', value: '51,200', date: '2026-07-15' },
      { period: 'Mai 2026', value: '54,600', date: '2026-06-15' },
    ],
  },
  {
    id: 'ancpi-bucharest-transactions',
    name: 'Tranzacții Imobiliare București (Municipiu)',
    code: 'ANCPI_B',
    category: 'real-estate',
    categoryLabel: 'Piața Imobiliară',
    value: '10,685',
    unit: 'imobile tranzacționate',
    previousValue: '11,450',
    change: '-765',
    changePct: '-6.68%',
    direction: 'down',
    period: 'August 2026',
    publishedAt: '2026-09-15',
    verifiedAt: '2026-10-06',
    sourceName: 'Agenția Națională de Cadastru și Publicitate Imobiliară (ANCPI)',
    sourceUrl: 'https://www.ancpi.ro/statistici/',
    sourceType: 'PRIMARY_GOV',
    confidence: 'MAXIMUM',
    status: 'LATEST OFFICIAL',
    whatItMeans: 'Unități individuale și terenuri tranzacționate în Capitală.',
    whyItMatters: 'Bucureștiul concentrează peste 20% din volumul tranzacțional național și dă tonul tendințelor de preț.',
    notes: 'Date oficiale ANCPI.',
    history: [
      { period: 'August 2026', value: '10,685', date: '2026-09-15' },
      { period: 'Iulie 2026', value: '11,450', date: '2026-08-15' },
      { period: 'Iunie 2026', value: '10,120', date: '2026-07-15' },
    ],
  },
  {
    id: 'ancpi-bucharest-ilfov-transactions',
    name: 'Tranzacții Imobiliare Aglomerarea București + Ilfov',
    code: 'ANCPI_B_IF',
    category: 'real-estate',
    categoryLabel: 'Piața Imobiliară',
    value: '15,120',
    unit: 'imobile tranzacționate',
    previousValue: '16,200',
    change: '-1,080',
    changePct: '-6.67%',
    direction: 'down',
    period: 'August 2026',
    publishedAt: '2026-09-15',
    verifiedAt: '2026-10-06',
    sourceName: 'Agenția Națională de Cadastru și Publicitate Imobiliară (ANCPI)',
    sourceUrl: 'https://www.ancpi.ro/statistici/',
    sourceType: 'PRIMARY_GOV',
    confidence: 'MAXIMUM',
    status: 'LATEST OFFICIAL',
    whatItMeans: 'Volumul cumulat al tranzacțiilor din Capitală și județul Ilfov (zona metropolitană).',
    whyItMatters: 'Reflectă cererea consolidată pe segmentul rezidențial extins (case, vile, ansambluri noi periferice).',
    notes: 'Suma tranzacțiilor București (10.685) + Ilfov (4.435) din registrul ANCPI.',
  },
  {
    id: 'ins-building-permits-res',
    name: 'Autorizații de Construire pentru Clădiri Rezidențiale',
    code: 'INS_PERMITS',
    category: 'real-estate',
    categoryLabel: 'Piața Imobiliară',
    value: '3,280',
    unit: 'autorizații eliberate',
    previousValue: '3,150',
    change: '+130',
    changePct: '+4.13%',
    direction: 'up',
    period: 'Iulie 2026',
    publishedAt: '2026-08-30',
    verifiedAt: '2026-10-06',
    sourceName: 'Institutul Național de Statistică (INS)',
    sourceUrl: 'https://insse.ro/cms/ro/comunicate-de-presa',
    sourceType: 'STATISTICAL_OFFICE',
    confidence: 'MAXIMUM',
    status: 'LATEST OFFICIAL',
    whatItMeans: 'Numărul autorizațiilor de construire eliberate de autoritățile locale pentru locuințe.',
    whyItMatters: 'Anticipează oferta viitoare de locuințe ce urmează să fie livrată în următorii 1-3 ani.',
    notes: 'Comunicat statistic lunar INS.',
  },
  {
    id: 'ins-construction-volume-index',
    name: 'Indicele Volumului Lucrărilor de Construcții',
    code: 'INS_CONST_IDX',
    category: 'real-estate',
    categoryLabel: 'Piața Imobiliară',
    value: '+3.80%',
    unit: '% an/an',
    previousValue: '+3.20%',
    change: '+0.60%',
    changePct: '+18.75%',
    direction: 'up',
    period: 'Trimestrul II 2026',
    publishedAt: '2026-08-20',
    verifiedAt: '2026-10-06',
    sourceName: 'Institutul Național de Statistică (INS)',
    sourceUrl: 'https://insse.ro/cms/ro/comunicate-de-presa',
    sourceType: 'STATISTICAL_OFFICE',
    confidence: 'MAXIMUM',
    status: 'LATEST OFFICIAL',
    whatItMeans: 'Dinamica activității în sectorul de construcții (rezidențial, nerezidențial și infrastructură).',
    whyItMatters: 'Creșterea este tractată în principal de infrastructura inginerească și proiectele de utilitate publică.',
    notes: 'Serie brută INS.',
  },
  {
    id: 'bnr-mortgage-credit-stock',
    name: 'Soldul Creditelor pentru Locuințe Acordate Populației',
    code: 'BNR_MORT_STOCK',
    category: 'real-estate',
    categoryLabel: 'Piața Imobiliară',
    value: '109.8 Mld RON',
    unit: 'Miliarde RON',
    previousValue: '108.9 Mld RON',
    change: '+0.9 Mld RON',
    changePct: '+0.83%',
    direction: 'up',
    period: 'August 2026',
    publishedAt: '2026-09-25',
    verifiedAt: '2026-10-06',
    sourceName: 'Banca Națională a României (BNR)',
    sourceUrl: 'https://www.bnr.ro/Financial-info-5682.aspx',
    sourceType: 'CENTRAL_BANK',
    confidence: 'MAXIMUM',
    status: 'LATEST OFFICIAL',
    whatItMeans: 'Valoarea totală a creditelor ipotecare și imobiliare aflate în derulare în sistemul bancar.',
    whyItMatters: 'Demonstrează că peste 85% din portofoliul ipotecar este denominat în monedă națională (fără risc valutar direct).',
    notes: 'Statistici monetare agregate din bilanțul sistemului bancar publicate de BNR.',
  },

  // ==========================================
  // 4. MARKETS & BENCHMARK ASSETS
  // ==========================================
  {
    id: 'market-bvb-bet',
    name: 'Indicele BET (Bursa de Valori București)',
    code: 'BET_BVB',
    category: 'markets',
    categoryLabel: 'Piețe & Burse',
    value: '18,450.20',
    unit: 'puncte',
    previousValue: '18,331.00',
    change: '+119.20',
    changePct: '+0.65%',
    direction: 'up',
    period: 'Ședința de Tranzacționare BVB',
    publishedAt: '2026-10-06',
    verifiedAt: '2026-10-06',
    sourceName: 'Bursa de Valori București (BVB)',
    sourceUrl: 'https://www.bvb.ro',
    sourceType: 'EXCHANGE',
    confidence: 'MAXIMUM',
    status: 'LAST CLOSE',
    whatItMeans: 'Principalul indice al pieței locale de capital, reflectând cele mai lichide 20 de companii românești.',
    whyItMatters: 'Barometrul performanței economiei românești corporative (TLV, H2O, SNP, SNG, ONE etc.).',
    notes: 'Cotație oficială la închiderea ședinței BVB.',
  },
  {
    id: 'market-bvb-bet-tr',
    name: 'Indicele BET-TR (Total Return cu Dividende Reinvestite)',
    code: 'BET_TR',
    category: 'markets',
    categoryLabel: 'Piețe & Burse',
    value: '39,820.50',
    unit: 'puncte',
    previousValue: '39,535.80',
    change: '+284.70',
    changePct: '+0.72%',
    direction: 'up',
    period: 'Ședința de Tranzacționare BVB',
    publishedAt: '2026-10-06',
    verifiedAt: '2026-10-06',
    sourceName: 'Bursa de Valori București (BVB)',
    sourceUrl: 'https://www.bvb.ro',
    sourceType: 'EXCHANGE',
    confidence: 'MAXIMUM',
    status: 'LAST CLOSE',
    whatItMeans: 'Include randamentul prețului acțiunilor componente plus dividendele brute distribuite.',
    whyItMatters: 'Indicatorul relevant pentru investitorii pe termen lung la BVB (+19.4% YTD).',
    notes: 'Indice de randament total calculat de BVB.',
  },
  {
    id: 'market-bvb-bet-fi',
    name: 'Indicele BET-FI (Societăți de Investiții Financiare)',
    code: 'BET_FI',
    category: 'markets',
    categoryLabel: 'Piețe & Burse',
    value: '62,410.00',
    unit: 'puncte',
    previousValue: '62,285.00',
    change: '+125.00',
    changePct: '+0.20%',
    direction: 'up',
    period: 'Ședința de Tranzacționare BVB',
    publishedAt: '2026-10-06',
    verifiedAt: '2026-10-06',
    sourceName: 'Bursa de Valori București (BVB)',
    sourceUrl: 'https://www.bvb.ro',
    sourceType: 'EXCHANGE',
    confidence: 'MAXIMUM',
    status: 'LAST CLOSE',
    whatItMeans: 'Indicele sectorial care urmărește fondurile de investiții alternative (fostele SIF-uri) și Fondul Proprietatea.',
    whyItMatters: 'Reflectă discounturile de tranzacționare față de activul net (VAN) ale marilor holdinguri financiare.',
    notes: 'Indice sectorial BVB.',
  },
  {
    id: 'market-sp500',
    name: 'Indicele S&P 500 (SUA)',
    code: 'SPX',
    category: 'markets',
    categoryLabel: 'Piețe & Burse',
    value: '5,580.40',
    unit: 'puncte',
    previousValue: '5,557.00',
    change: '+23.40',
    changePct: '+0.42%',
    direction: 'up',
    period: 'Ședința Bursieră SUA (NYSE/Nasdaq)',
    publishedAt: '2026-10-06',
    verifiedAt: '2026-10-06',
    sourceName: 'S&P Dow Jones Indices',
    sourceUrl: 'https://www.spglobal.com',
    sourceType: 'EXCHANGE',
    confidence: 'MAXIMUM',
    status: 'LAST CLOSE',
    whatItMeans: 'Cele mai mari 500 de companii americane cotate la bursele din New York.',
    whyItMatters: 'Referința globală pentru evaluarea acțiunilor și apetitul internațional de risc.',
    notes: 'Cotație de închidere oficială.',
  },
  {
    id: 'market-nasdaq',
    name: 'Nasdaq Composite',
    code: 'IXIC',
    category: 'markets',
    categoryLabel: 'Piețe & Burse',
    value: '17,640.80',
    unit: 'puncte',
    previousValue: '17,492.10',
    change: '+148.70',
    changePct: '+0.85%',
    direction: 'up',
    period: 'Ședința Bursieră SUA',
    publishedAt: '2026-10-06',
    verifiedAt: '2026-10-06',
    sourceName: 'Nasdaq Inc.',
    sourceUrl: 'https://www.nasdaq.com',
    sourceType: 'EXCHANGE',
    confidence: 'MAXIMUM',
    status: 'LAST CLOSE',
    whatItMeans: 'Indicele acțiunilor tehnologice, semiconductoarelor și platformelor digitale globale.',
    whyItMatters: 'Evoluția determină cotațiile gigantilor din AI, software și cloud.',
    notes: 'Cotație oficială Nasdaq.',
  },
  {
    id: 'market-dax',
    name: 'DAX 40 (Germania)',
    code: 'DAX_DE',
    category: 'markets',
    categoryLabel: 'Piețe & Burse',
    value: '18,320.60',
    unit: 'puncte',
    previousValue: '18,264.00',
    change: '+56.60',
    changePct: '+0.31%',
    direction: 'up',
    period: 'Ședința Bursieră Deutsche Börse',
    publishedAt: '2026-10-06',
    verifiedAt: '2026-10-06',
    sourceName: 'Deutsche Börse AG',
    sourceUrl: 'https://www.boerse-frankfurt.de',
    sourceType: 'EXCHANGE',
    confidence: 'MAXIMUM',
    status: 'LAST CLOSE',
    whatItMeans: 'Indicele celor mai mari 40 de concerne industriale și tehnologice germane.',
    whyItMatters: 'Germania este principalul partener comercial al României; activitatea DAX reflectă cererea europeană.',
    notes: 'Cotație Xetra oficială.',
  },
  {
    id: 'market-stoxx600',
    name: 'STOXX Europe 600',
    code: 'SXXP',
    category: 'markets',
    categoryLabel: 'Piețe & Burse',
    value: '520.40',
    unit: 'puncte',
    previousValue: '519.10',
    change: '+1.30',
    changePct: '+0.25%',
    direction: 'up',
    period: 'Ședința Bursieră Europeană',
    publishedAt: '2026-10-06',
    verifiedAt: '2026-10-06',
    sourceName: 'STOXX Ltd.',
    sourceUrl: 'https://www.stoxx.com',
    sourceType: 'EXCHANGE',
    confidence: 'MAXIMUM',
    status: 'LAST CLOSE',
    whatItMeans: 'Indice pan-european ce acoperă 600 de companii mari, medii și mici din 17 state europene.',
    whyItMatters: 'Barometrul sănătății corporative la nivelul întregului continent european.',
    notes: 'Cotație de închidere pan-europeană.',
  },
  {
    id: 'fx-eur-usd',
    name: 'Paritatea Valutară EUR / USD',
    code: 'EUR_USD',
    category: 'markets',
    categoryLabel: 'Piețe & Burse',
    value: '1.0860',
    unit: 'USD',
    previousValue: '1.0838',
    change: '+0.0022',
    changePct: '+0.20%',
    direction: 'up',
    period: 'Piața Valutară Internațională',
    publishedAt: '2026-10-06',
    verifiedAt: '2026-10-06',
    sourceName: 'Banca Centrală Europeană (BCE)',
    sourceUrl: 'https://www.ecb.europa.eu',
    sourceType: 'CENTRAL_BANK',
    confidence: 'MAXIMUM',
    status: 'LAST CLOSE',
    whatItMeans: 'Cea mai tranzacționată pereche valutară din lume (euro vs dolar american).',
    whyItMatters: 'Stabilește raportul de putere dintre fluxurile comerciale europene și cele denominate în dolari.',
    notes: 'Referință oficială BCE.',
  },
  {
    id: 'comm-gold',
    name: 'Aur Spot (XAU / USD)',
    code: 'GOLD_USD',
    category: 'commodities',
    categoryLabel: 'Mărfuri & Active de Rezervă',
    value: '2,480.50',
    unit: 'USD / uncie (oz)',
    previousValue: '2,464.50',
    change: '+16.00',
    changePct: '+0.65%',
    direction: 'up',
    period: 'Piața Metalelor Prețioase (LBMA)',
    publishedAt: '2026-10-06',
    verifiedAt: '2026-10-06',
    sourceName: 'London Bullion Market Association (LBMA)',
    sourceUrl: 'https://www.lbma.org.uk',
    sourceType: 'EXCHANGE',
    confidence: 'HIGH',
    status: 'LAST CLOSE',
    whatItMeans: 'Cotația de referință internațională pentru uncia troy de aur fin (31.1 grame).',
    whyItMatters: 'Activ tradițional de rezervă și acoperire împotriva devalorizării monetare (+18.5% YTD).',
    notes: 'Fixing oficial LBMA.',
  },
  {
    id: 'comm-brent',
    name: 'Petrol Brut Brent',
    code: 'BRENT_OIL',
    category: 'commodities',
    categoryLabel: 'Mărfuri & Active de Rezervă',
    value: '76.80',
    unit: 'USD / baril (bbl)',
    previousValue: '75.85',
    change: '+0.95',
    changePct: '+1.25%',
    direction: 'up',
    period: 'Piața Energetică ICE Futures',
    publishedAt: '2026-10-06',
    verifiedAt: '2026-10-06',
    sourceName: 'Intercontinental Exchange (ICE)',
    sourceUrl: 'https://www.theice.com',
    sourceType: 'EXCHANGE',
    confidence: 'HIGH',
    status: 'LAST CLOSE',
    whatItMeans: 'Cotația de referință globală pentru țițeiul extras din Marea Nordului.',
    whyItMatters: 'Impact direct asupra prețului carburanților la pompă în România și asupra veniturilor OMV Petrom (SNP).',
    notes: 'Contracte futures ICE Brent.',
  },
  {
    id: 'crypto-bitcoin',
    name: 'Bitcoin (BTC / USD)',
    code: 'BTC_USD',
    category: 'commodities',
    categoryLabel: 'Mărfuri & Active de Rezervă',
    value: '63,850.00',
    unit: 'USD',
    previousValue: '62,940.00',
    change: '+910.00',
    changePct: '+1.45%',
    direction: 'up',
    period: 'Piața Activelor Digitale',
    publishedAt: '2026-10-06',
    verifiedAt: '2026-10-06',
    sourceName: 'CoinGecko / Indice Agregat',
    sourceUrl: 'https://www.coingecko.com',
    sourceType: 'EXCHANGE',
    confidence: 'HIGH',
    status: 'LAST CLOSE',
    whatItMeans: 'Principalul activ criptografic descentralizat după capitalizarea de piață.',
    whyItMatters: 'Monitorizat ca barometru al lichidității globale și apetitului pentru active alternative de risc.',
    notes: 'Preț mediu ponderat cu volumul pe 24h.',
  },
];

// ==========================================
// 5. AIX INTELLIGENCE — DAILY BRIEFING
// ==========================================
export const dailyBriefingItems: BriefingItem[] = [
  {
    id: 'brief-1-macro',
    category: 'romania-macro',
    categoryLabel: 'Economia României',
    headline: 'Dezinflația stabilizează IPC la 5,10%, iar creșterea PIB este confirmată la +1,50% în S1',
    summary: 'Institutul Național de Statistică (INS) a raportat temperarea inflației anuale la 5,10%, pe fondul stabilizării prețurilor la alimente și energie. Totodată, avansul PIB de +1,5% în primul semestru reflectă susținerea economiei prin marile proiecte de infrastructură PNRR.',
    whyItMatters: 'Reducerea presiunii inflaționiste protejează veniturile reale ale populației și acordă băncii centrale spațiu de manevră pentru relaxarea dobânzilor în trimestrele următoare.',
    sourceName: 'Institutul Național de Statistică (INS)',
    sourceUrl: 'https://insse.ro/cms/ro/comunicate-de-presa',
    publicationDate: '2026-09-11',
    reportingPeriod: 'August 2026 & Semestrul I 2026',
  },
  {
    id: 'brief-2-real-estate',
    category: 'real-estate',
    categoryLabel: 'Piața Imobiliară',
    headline: 'ANCPI raportează 52.430 de imobile tranzacționate național; Bucureștiul concentrează 10.685 de unități',
    summary: 'Registrul cadastral ANCPI arată o activitate susținută pe segmentul rezidențial din Capitală și Ilfov (15.120 tranzacții cumulate), în timp ce volumul lucrărilor de construcții la nivel național înregistrează un plus de +3,8% conform INS.',
    whyItMatters: 'Lichiditatea rămâne concentrată pe poli urbani mari cu randamente de închiriere între 5,8% și 7,2%, pe fondul unei oferte noi limitate de ritmul avizărilor urbanistice.',
    sourceName: 'ANCPI & INS',
    sourceUrl: 'https://www.ancpi.ro/statistici/',
    publicationDate: '2026-09-15',
    reportingPeriod: 'August 2026 & T2 2026',
  },
  {
    id: 'brief-3-credit-bnr',
    category: 'money-credit',
    categoryLabel: 'Bani & BNR',
    headline: 'BNR menține dobânda de politică monetară la 6,50%; IRCC este stabilit la 5,86% pentru T4',
    summary: 'Consiliul de Administrație al Băncii Naționale a României a decis menținerea ratei cheie la 6,50% pe an, în timp ce indicele IRCC aplicabil în trimestrul IV se situează la 5,86%, iar ROBOR 3M se tranzacționează în jurul valorii de 5,58%.',
    whyItMatters: 'Păstrarea dobânzii aduce predictibilitate costurilor de finanțare pentru companii și debitorii cu credite ipotecare legate de indicii monetari.',
    sourceName: 'Banca Națională a României (BNR)',
    sourceUrl: 'https://www.bnr.ro/Financial-info-5682.aspx',
    publicationDate: '2026-10-04',
    reportingPeriod: 'Octombrie 2026 & T4 2026',
  },
  {
    id: 'brief-4-bvb-markets',
    category: 'markets',
    categoryLabel: 'Bursa de Valori București',
    headline: 'Indicele BET Total Return depășește 39.800 puncte, susținut de rezultatele financiare semestriale din energie și bănci',
    summary: 'Banca Transilvania (TLV) raportează 2,15 miliarde RON profit net pe S1, Hidroelectrica (H2O) atinge 5,15 miliarde RON venituri, iar OMV Petrom (SNP) înaintează cu investiția strategică Neptun Deep.',
    whyItMatters: 'Multiplii de evaluare la BVB (P/E mediu 7-9x) continuă să ofere un profil solid de dividende comparativ cu piețele emergente din regiune.',
    sourceName: 'Bursa de Valori București (BVB) & Raportări Emitenți',
    sourceUrl: 'https://www.bvb.ro',
    publicationDate: '2026-10-06',
    reportingPeriod: 'Semestrul I 2026 & Ședința BVB',
  },
  {
    id: 'brief-5-global',
    category: 'markets',
    categoryLabel: 'Piețe Globale & Mărfuri',
    headline: 'Aurul atinge 2.480 USD/uncie, în timp ce S&P 500 și DAX își mențin trendul pe fondul relaxării monetare a marilor bănci centrale',
    summary: 'BCE a operat o reducere de 25 bps a dobânzii la 3,50%, iar Rezerva Federală a inițiat ciclul de relaxare monetară. Țițeiul Brent consolidează în zona de 76,80 USD/baril.',
    whyItMatters: 'Politica de scădere a costului dolarului și euro susține lichiditatea globală și fluxurile de capital către piețele de frontieră și emergente din Europa Centrală și de Est.',
    sourceName: 'BCE, Fed & Piețe Internaționale',
    sourceUrl: 'https://www.ecb.europa.eu',
    publicationDate: '2026-10-06',
    reportingPeriod: 'Octombrie 2026',
  },
];

// ==========================================
// 6. DAILY MARKET CLOSE TICKER
// ==========================================
export const dailyMarketCloseItems: MarketCloseItem[] = [
  {
    symbol: 'BET',
    name: 'BVB BET Index',
    value: '18,450.20',
    unit: 'pct',
    change: '+119.20',
    changePct: '+0.65%',
    direction: 'up',
    status: 'LAST CLOSE',
    verifiedAt: '2026-10-06 17:30 EEST',
    source: 'BVB',
  },
  {
    symbol: 'EUR/RON',
    name: 'Curs BNR',
    value: '4.9765',
    unit: 'RON',
    change: '+0.0005',
    changePct: '+0.01%',
    direction: 'up',
    status: 'VERIFIED',
    verifiedAt: '2026-10-06 13:00 EEST',
    source: 'BNR',
  },
  {
    symbol: 'USD/RON',
    name: 'Curs BNR',
    value: '4.5420',
    unit: 'RON',
    change: '-0.0060',
    changePct: '-0.13%',
    direction: 'down',
    status: 'VERIFIED',
    verifiedAt: '2026-10-06 13:00 EEST',
    source: 'BNR',
  },
  {
    symbol: 'GOLD',
    name: 'Aur (XAU/USD)',
    value: '2,480.50',
    unit: 'USD/oz',
    change: '+16.00',
    changePct: '+0.65%',
    direction: 'up',
    status: 'LAST CLOSE',
    verifiedAt: '2026-10-06 18:00 EEST',
    source: 'LBMA',
  },
  {
    symbol: 'BRENT',
    name: 'Petrol Brent',
    value: '76.80',
    unit: 'USD/bbl',
    change: '+0.95',
    changePct: '+1.25%',
    direction: 'up',
    status: 'LAST CLOSE',
    verifiedAt: '2026-10-06 18:00 EEST',
    source: 'ICE',
  },
  {
    symbol: 'BTC',
    name: 'Bitcoin',
    value: '63,850.00',
    unit: 'USD',
    change: '+910.00',
    changePct: '+1.45%',
    direction: 'up',
    status: 'LAST CLOSE',
    verifiedAt: '2026-10-06 18:00 EEST',
    source: 'CoinGecko',
  },
];

// Helper Query Functions
export function getAllIndicators(): DataIndicator[] {
  return comprehensiveIndicators;
}

export function getIndicatorsByCategory(category: IndicatorCategory): DataIndicator[] {
  return comprehensiveIndicators.filter((i) => i.category === category);
}

export function getIndicatorById(id: string): DataIndicator | undefined {
  return comprehensiveIndicators.find((i) => i.id === id);
}

export function getDailyBriefing(): BriefingItem[] {
  return dailyBriefingItems;
}

export function getMarketClose(): MarketCloseItem[] {
  return dailyMarketCloseItems;
}
