import { Article } from "./models/article";
import {
  Author,
  PodcastEpisode,
  RadioShow,
  VideoItem,
  MarketItem,
  Company,
  EconomicEvent,
  AiXBriefing,
} from "./models/media-types";

export const authors: Author[] = [
  {
    id: "cristian-vaduva",
    slug: "cristian-vaduva",
    name: "Cristian Văduva",
    role: "Editor-in-Chief & Founder",
    bio: "Economic analyst and media executive specializing in Central & Eastern European capital dynamics, monetary policy, and private equity.",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&auto=format&fit=crop",
    expertise: ["Macroeconomics", "Capital Markets", "Private Equity", "CEE Policy"],
    twitter: "@aixmedia",
    linkedin: "https://linkedin.com/in/aixmedia",
  },
  {
    id: "elena-popescu",
    slug: "elena-popescu",
    name: "Elena Popescu",
    role: "Head of Real Estate Intelligence",
    bio: "Senior analyst tracking institutional property flows, commercial yields, logistics hubs, and urban master plans across CEE.",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=400&auto=format&fit=crop",
    expertise: ["Real Estate Yields", "Logistics", "Urban Transformation", "PropTech"],
    linkedin: "https://linkedin.com/in/elena-popescu-aix",
  },
  {
    id: "alexandru-ionescu",
    slug: "alexandru-ionescu",
    name: "Alexandru Ionescu",
    role: "Chief Capital Markets Strategist",
    bio: "Former investment banker focusing on Bucharest Stock Exchange (BVB) equities, European sovereign debt, and currency dynamics.",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=400&auto=format&fit=crop",
    expertise: ["BVB Index", "Fixed Income", "Central Banking", "Commodities"],
    twitter: "@alex_ionescu_aix",
  },
];

export const articles: Article[] = [
  {
    id: "art-1",
    title: "Romania's Economic Horizon 2026: Capital Allocation & Macro Realities",
    slug: "romania-economic-horizon-2026-capital-allocation",
    category: "news",
    categoryLabel: "Macro Intelligence",
    authorId: "cristian-vaduva",
    authorName: "Cristian Văduva",
    authorRole: "Editor-in-Chief",
    authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&auto=format&fit=crop",
    excerpt: "An executive briefing on Romania's macro trajectory, fiscal consolidation, and how CEE capital flows are adapting to evolving European monetary policy.",
    content: `
# Romania's Economic Horizon 2026

As Central and Eastern Europe navigates a complex macroeconomic environment, Romania stands at a strategic inflection point. Sustained FDI inflows, public infrastructure expansion funded by EU recovery funds, and steady domestic consumption are driving resilience across key sectors.

## Key Macro Pillars

1. **Monetary Rate Trajectory**: BNR's cautious stance has stabilized EUR/RON exchange rates while keeping inflation on a downward slope toward 5%.
2. **Capital Markets Growth**: The Bucharest Stock Exchange (BVB) continues to attract record institutional participation following high-profile listings.
3. **Infrastructure Supercycle**: Major highway, logistics, and renewable energy developments are reducing transport bottlenecks and unlocking regional economic hubs.

> "Institutional investors are looking past short-term volatility toward CEE's long-term yield advantage and infrastructure convergence." — *AiX Research*
    `,
    coverImage: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1200&auto=format&fit=crop",
    publishedAt: "2026-08-05",
    readTime: "6 min read",
    views: 18400,
    featured: true,
    breaking: true,
    trending: true,
  },
  {
    id: "art-2",
    title: "Why Northern Bucharest Real Estate Continues to Attract Institutional Capital",
    slug: "northern-bucharest-real-estate-capital-flows",
    category: "real-estate",
    categoryLabel: "Real Estate Intelligence",
    authorId: "elena-popescu",
    authorName: "Elena Popescu",
    authorRole: "Head of RE Intelligence",
    authorAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=400&auto=format&fit=crop",
    excerpt: "Institutional transaction analysis examining office conversions, mixed-use luxury developments, and prime yields in Bucharest's growth corridor.",
    content: `
# Northern Bucharest Property Dynamics

Northern Bucharest remains the engine of high-end real estate transactions in Romania. Driven by corporate headquarters demand and high-net-worth buyers, prime developers are pioneering mixed-use urban transformations.

## Market Metrics

- **Prime Office Yields**: 7.25%
- **Luxury Residential Price Growth**: +6.8% YoY
- **Logistics Vacancy**: 4.8%
    `,
    coverImage: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=1200&auto=format&fit=crop",
    publishedAt: "2026-08-04",
    readTime: "5 min read",
    views: 11200,
    featured: true,
    trending: true,
  },
  {
    id: "art-3",
    title: "BVB Market Liquidity: Institutional Pension Allocation & Equity Expansion",
    slug: "bvb-market-liquidity-pension-allocation",
    category: "markets",
    categoryLabel: "Capital Markets",
    authorId: "alexandru-ionescu",
    authorName: "Alexandru Ionescu",
    authorRole: "Chief Markets Strategist",
    authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=400&auto=format&fit=crop",
    excerpt: "How Pillar II pension funds and international institutional buyers are driving liquidity records on the Bucharest Stock Exchange.",
    content: "Detailed breakdown of stock performance, valuation ratios, and international capital flows...",
    coverImage: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?q=80&w=1200&auto=format&fit=crop",
    publishedAt: "2026-08-03",
    readTime: "7 min read",
    views: 9400,
    featured: true,
  },
  {
    id: "art-4",
    title: "Venture & Private Equity Trends in CEE: Where Capital is Flowing",
    slug: "venture-private-equity-trends-cee",
    category: "investments",
    categoryLabel: "Investments & Wealth",
    authorId: "cristian-vaduva",
    authorName: "Cristian Văduva",
    authorRole: "Editor-in-Chief",
    authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&auto=format&fit=crop",
    excerpt: "Private capital allocation analysis across fintech, green energy tech, and regional enterprise software scaleups.",
    content: "Analysis of venture rounds and private equity dry powder across CEE...",
    coverImage: "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?q=80&w=1200&auto=format&fit=crop",
    publishedAt: "2026-08-02",
    readTime: "4 min read",
    views: 7300,
  },
  {
    id: "art-5",
    title: "Mortgage Market Shifts: How Interest Rate Stabilization Influences Buyer Behavior",
    slug: "mortgage-market-shifts-interest-rate-stabilization",
    category: "finance",
    categoryLabel: "Finance & Monetary Policy",
    authorId: "alexandru-ionescu",
    authorName: "Alexandru Ionescu",
    authorRole: "Chief Markets Strategist",
    authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=400&auto=format&fit=crop",
    excerpt: "An analytical study of fixed-rate banking products, IRCC trajectories, and debt service ratios among Romanian homebuyers.",
    content: "Macro analysis of mortgage interest rates, banking solvency, and buyer sentiment...",
    coverImage: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?q=80&w=1200&auto=format&fit=crop",
    publishedAt: "2026-08-01",
    readTime: "5 min read",
    views: 8100,
  },
  {
    id: "art-6",
    title: "Romanian Enterprise Champions Scaling Regionally: The M&A Playbook",
    slug: "romanian-enterprise-champions-scaling-regionally",
    category: "business",
    categoryLabel: "Business & Enterprise",
    authorId: "cristian-vaduva",
    authorName: "Cristian Văduva",
    authorRole: "Editor-in-Chief",
    authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&auto=format&fit=crop",
    excerpt: "Case studies of top Romanian tech, logistics, and retail groups acquiring assets in Poland, Hungary, and Germany.",
    content: "Strategy teardown of regional acquisitions...",
    coverImage: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=1200&auto=format&fit=crop",
    publishedAt: "2026-07-31",
    readTime: "6 min read",
    views: 6500,
  },
];

export const marketItems: MarketItem[] = [
  // BVB Indices
  { symbol: "BET", name: "Bucharest Exchange Trading", value: "18,420.50", changeDaily: "+2.30%", changeWeekly: "+3.8%", changeMonthly: "+6.1%", changeYearly: "+24.5%", isPositive: true, category: "indices", status: "OPEN", chartPoints: [18000, 18120, 18250, 18380, 18420] },
  { symbol: "BET-TR", name: "BET Total Return Index", value: "39,850.10", changeDaily: "+2.45%", changeWeekly: "+4.1%", changeMonthly: "+7.2%", changeYearly: "+28.2%", isPositive: true, category: "indices", status: "OPEN", chartPoints: [38500, 39000, 39400, 39850] },
  { symbol: "BET-FI", name: "BET Financial Investment", value: "62,140.00", changeDaily: "+1.15%", changeWeekly: "+2.2%", changeMonthly: "+4.5%", changeYearly: "+18.9%", isPositive: true, category: "indices", status: "OPEN", chartPoints: [61000, 61500, 62140] },
  { symbol: "BET-NG", name: "BET Energy & Utilities", value: "1,240.80", changeDaily: "+0.85%", changeWeekly: "+1.9%", changeMonthly: "+3.8%", changeYearly: "+19.4%", isPositive: true, category: "indices", status: "OPEN", chartPoints: [1200, 1220, 1240] },

  // Currencies
  { symbol: "EUR/RON", name: "Euro / Romanian Leu", value: "4.9765", changeDaily: "+0.02%", changeWeekly: "-0.01%", changeMonthly: "+0.15%", changeYearly: "+0.85%", isPositive: true, category: "currencies", status: "OPEN" },
  { symbol: "USD/RON", name: "US Dollar / Romanian Leu", value: "4.5830", changeDaily: "-0.11%", changeWeekly: "-0.45%", changeMonthly: "-1.20%", changeYearly: "-2.10%", isPositive: false, category: "currencies", status: "OPEN" },
  { symbol: "GBP/RON", name: "British Pound / Leu", value: "5.8240", changeDaily: "+0.14%", changeWeekly: "+0.50%", changeMonthly: "+0.90%", changeYearly: "+3.20%", isPositive: true, category: "currencies", status: "OPEN" },
  { symbol: "CHF/RON", name: "Swiss Franc / Leu", value: "5.2110", changeDaily: "+0.08%", changeWeekly: "+0.22%", changeMonthly: "+0.60%", changeYearly: "+2.40%", isPositive: true, category: "currencies", status: "OPEN" },

  // Rates & Macro
  { symbol: "ROBOR 3M", name: "Interbank Rate 3M", value: "5.58%", changeDaily: "-0.05%", changeWeekly: "-0.12%", changeMonthly: "-0.30%", changeYearly: "-1.10%", isPositive: true, category: "rates", status: "OPEN" },
  { symbol: "ROBOR 6M", name: "Interbank Rate 6M", value: "5.64%", changeDaily: "-0.04%", changeWeekly: "-0.10%", changeMonthly: "-0.28%", changeYearly: "-1.05%", isPositive: true, category: "rates", status: "OPEN" },
  { symbol: "IRCC", name: "Consumer Credit Benchmark", value: "5.86%", changeDaily: "-0.11%", changeWeekly: "-0.11%", changeMonthly: "-0.11%", changeYearly: "-0.45%", isPositive: true, category: "rates", status: "OPEN" },
  { symbol: "BNR RATE", name: "National Bank Key Rate", value: "6.50%", changeDaily: "0.00%", changeWeekly: "0.00%", changeMonthly: "0.00%", changeYearly: "-0.50%", isPositive: true, category: "rates", status: "OPEN" },
  { symbol: "RO 10Y BOND", name: "Romanian Govt 10Y Bond", value: "6.42%", changeDaily: "-0.08%", changeWeekly: "-0.15%", changeMonthly: "-0.40%", changeYearly: "-1.20%", isPositive: true, category: "bonds", status: "OPEN" },
  { symbol: "CPI INFLATION", name: "Romania Annual CPI", value: "5.10%", changeDaily: "-0.40%", changeWeekly: "-0.40%", changeMonthly: "-0.80%", changeYearly: "-3.20%", isPositive: true, category: "rates", status: "OPEN" },

  // Commodities
  { symbol: "XAU/USD", name: "Gold Spot", value: "$2,348.40", changeDaily: "+0.60%", changeWeekly: "+1.8%", changeMonthly: "+4.2%", changeYearly: "+19.8%", isPositive: true, category: "commodities", status: "OPEN" },
  { symbol: "XAG/USD", name: "Silver Spot", value: "$27.43", changeDaily: "+1.10%", changeWeekly: "+3.2%", changeMonthly: "+6.5%", changeYearly: "+22.4%", isPositive: true, category: "commodities", status: "OPEN" },
  { symbol: "BRENT", name: "Brent Crude Oil", value: "$84.72", changeDaily: "-1.20%", changeWeekly: "-2.4%", changeMonthly: "-4.1%", changeYearly: "-8.5%", isPositive: false, category: "commodities", status: "OPEN" },
  { symbol: "NG", name: "Natural Gas (TTF)", value: "€34.20", changeDaily: "+0.45%", changeWeekly: "+1.1%", changeMonthly: "+3.0%", changeYearly: "-12.0%", isPositive: true, category: "commodities", status: "OPEN" },

  // Crypto & Global
  { symbol: "BTC/USD", name: "Bitcoin", value: "$64,250", changeDaily: "+3.10%", changeWeekly: "+8.4%", changeMonthly: "+14.2%", changeYearly: "+112.5%", isPositive: true, category: "crypto", status: "OPEN" },
  { symbol: "ETH/USD", name: "Ethereum", value: "$3,480", changeDaily: "+2.40%", changeWeekly: "+6.1%", changeMonthly: "+11.8%", changeYearly: "+84.2%", isPositive: true, category: "crypto", status: "OPEN" },
  { symbol: "S&P 500", name: "S&P 500 Index", value: "5,611.80", changeDaily: "+0.80%", changeWeekly: "+1.5%", changeMonthly: "+3.2%", changeYearly: "+21.4%", isPositive: true, category: "global", status: "OPEN" },
  { symbol: "NASDAQ", name: "NASDAQ Composite", value: "17,890.40", changeDaily: "+1.20%", changeWeekly: "+2.4%", changeMonthly: "+4.8%", changeYearly: "+28.9%", isPositive: true, category: "global", status: "OPEN" },
  { symbol: "DAX", name: "DAX Performance Index", value: "18,890.30", changeDaily: "-0.40%", changeWeekly: "+0.2%", changeMonthly: "+1.8%", changeYearly: "+14.2%", isPositive: false, category: "global", status: "OPEN" },
];

export const radioShows: RadioShow[] = [
  {
    id: "show-1",
    title: "Markets Morning Briefing",
    host: "Cristian Văduva",
    airTime: "07:30 AM - 09:00 AM",
    status: "LIVE",
    description: "Real-time pre-market insights, global currency wrap, macroeconomic signals, and executive commentary before European trading opens.",
    audioStreamUrl: "https://stream.aixmedia.ro/live.mp3",
    coverImage: "https://images.unsplash.com/photo-1478737270239-2f02b77fc618?q=80&w=600&auto=format&fit=crop",
    category: "Markets Morning",
  },
  {
    id: "show-2",
    title: "CEO Talk: CEE Leadership Series",
    host: "Cristian Văduva",
    airTime: "10:30 AM - 11:30 AM",
    status: "UPCOMING",
    description: "In-depth conversations with founders, CEOs, and managing partners on strategy, M&A, and market expansion.",
    audioStreamUrl: "https://stream.aixmedia.ro/live.mp3",
    coverImage: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?q=80&w=600&auto=format&fit=crop",
    category: "CEO Talk",
  },
  {
    id: "show-3",
    title: "The Midday Property & Infrastructure Forum",
    host: "Elena Popescu",
    airTime: "12:30 PM - 01:30 PM",
    status: "UPCOMING",
    description: "Commercial real estate yield updates, logistics stock reports, and urban development analysis.",
    audioStreamUrl: "https://stream.aixmedia.ro/live.mp3",
    coverImage: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=600&auto=format&fit=crop",
    category: "Property Intelligence",
  },
  {
    id: "show-4",
    title: "Macro Weekly & Closing Bell Wrap",
    host: "Alexandru Ionescu",
    airTime: "05:30 PM - 07:00 PM",
    status: "REPLAY",
    description: "BVB closing Bell report, ROBOR trajectory, bond yields, and Wall Street opening commentary.",
    audioStreamUrl: "https://stream.aixmedia.ro/live.mp3",
    coverImage: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?q=80&w=600&auto=format&fit=crop",
    category: "Macro Weekly",
  },
];

export const podcastEpisodes: PodcastEpisode[] = [
  {
    id: "pod-1",
    title: "Building Regional Champions: Strategic M&A and Capital Growth",
    slug: "building-regional-champions-strategic-ma",
    showName: "The CEO Playbook",
    episodeNumber: 84,
    duration: "54 min",
    publishedAt: "2026-08-04",
    audioUrl: "https://media.aixmedia.ro/podcasts/ep84.mp3",
    coverImage: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?q=80&w=600&auto=format&fit=crop",
    description: "A conversation with leading CEE founders on expanding enterprise software companies across European markets.",
    host: "Cristian Văduva",
    guest: "Mihai Stoica, Founder & CEO",
    spotifyUrl: "https://spotify.com",
    appleUrl: "https://apple.com",
    keyQuote: "Cross-border M&A requires cultural integration just as much as financial synergy.",
    chapters: [
      { time: "00:00", title: "Introduction & Market Context" },
      { time: "12:15", title: "Cross-Border Valuation Multiples" },
      { time: "28:40", title: "Post-Merger Integration Playbook" },
      { time: "45:10", title: "Future Outlook for CEE Scaleups" },
    ],
    transcript: "Full transcript available for subscribers. In this episode we explore...",
  },
  {
    id: "pod-2",
    title: "Institutional Real Estate Allocation & Yield Dynamics in CEE",
    slug: "institutional-real-estate-allocation-yield-dynamics",
    showName: "Real Estate Intelligence Podcast",
    episodeNumber: 42,
    duration: "48 min",
    publishedAt: "2026-08-01",
    audioUrl: "https://media.aixmedia.ro/podcasts/ep42.mp3",
    coverImage: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=600&auto=format&fit=crop",
    description: "How international funds structure cap rates, debt financing, and logistics hub investments.",
    host: "Elena Popescu",
    guest: "Dan Radu, Managing Partner",
    spotifyUrl: "https://spotify.com",
    appleUrl: "https://apple.com",
    keyQuote: "Bucharest prime office yields at 7.25% present a compelling risk-adjusted premium over Western European capitals.",
  },
  {
    id: "pod-3",
    title: "Macroeconomic Policy & Inflation Targets: Central Bank Insights",
    slug: "macroeconomic-policy-inflation-targets",
    showName: "Macro Signals",
    episodeNumber: 29,
    duration: "62 min",
    publishedAt: "2026-07-25",
    audioUrl: "https://media.aixmedia.ro/podcasts/ep29.mp3",
    coverImage: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?q=80&w=600&auto=format&fit=crop",
    description: "Analyzing central bank rate decisions, liquidity buffers, and macroeconomic forecasts for 2026-2027.",
    host: "Alexandru Ionescu",
    guest: "Dr. Sorin Moldovan, Macroeconomist",
    spotifyUrl: "https://spotify.com",
    appleUrl: "https://apple.com",
  },
];

export const tvVideos: VideoItem[] = [
  {
    id: "vid-1",
    title: "Documentary Special: The Transformation of CEE Energy Infrastructure",
    slug: "cee-energy-infrastructure-transformation",
    youtubeId: "dQw4w9WgXcQ",
    duration: "28:15",
    publishedAt: "2026-08-04",
    category: "Documentary",
    playlistName: "AiX Investigations",
    description: "An investigative visual report on offshore gas, solar grid integration, and CEE energy independence.",
    thumbnailUrl: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "vid-2",
    title: "Studio Interview: BVB Leadership on Foreign Institutional Flows",
    slug: "bvb-leadership-foreign-institutional-flows",
    youtubeId: "dQw4w9WgXcQ",
    duration: "18:40",
    publishedAt: "2026-07-30",
    category: "CEO Interviews",
    playlistName: "CEO Studio Series",
    description: "Exclusive studio talk discussing exchange liquidity, pension fund rules, and new tech listings.",
    thumbnailUrl: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?q=80&w=800&auto=format&fit=crop",
  },
  {
    id: "vid-3",
    title: "Inside Bucharest's Commercial Hubs: A Visual Architecture Report",
    slug: "inside-bucharests-commercial-hubs",
    youtubeId: "dQw4w9WgXcQ",
    duration: "15:10",
    publishedAt: "2026-07-25",
    category: "Investigations",
    playlistName: "Urban Transformations",
    description: "On-site video exploration of award-winning mixed-use developments in Northern Bucharest.",
    thumbnailUrl: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=800&auto=format&fit=crop",
  },
];

export const companies: Company[] = [
  {
    id: "comp-1",
    slug: "banca-transilvania",
    symbol: "TLV",
    name: "Banca Transilvania",
    sector: "Banking & Financial Services",
    logo: "https://images.unsplash.com/photo-1541354329998-f4d9a9f9297f?q=80&w=300&auto=format&fit=crop",
    marketCap: "€5.8B",
    stockPrice: "28.40 RON",
    priceChange: "+1.8%",
    isPositive: true,
    ceo: "Ömer Tetik",
    headquarters: "Cluj-Napoca, Romania",
    description: "The largest banking group in Romania and top financial institution in CEE by assets.",
    revenue: "€1.85B",
    netIncome: "€580M",
    peRatio: "7.2x",
    dividendYield: "6.8%",
    timeline: [
      { year: "1993", event: "Founded in Cluj-Napoca by local entrepreneurs." },
      { year: "1997", event: "Listed on Bucharest Stock Exchange (BVB: TLV)." },
      { year: "2018", event: "Became #1 Bank in Romania after acquiring Volksbank & Bancpost." },
      { year: "2024", event: "Acquired OTP Bank Romania expanding total asset lead." },
    ],
  },
  {
    id: "comp-2",
    slug: "hidroelectrica",
    symbol: "H2O",
    name: "Hidroelectrica",
    sector: "Clean Energy & Hydroelectric",
    logo: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?q=80&w=300&auto=format&fit=crop",
    marketCap: "€11.4B",
    stockPrice: "128.50 RON",
    priceChange: "+2.4%",
    isPositive: true,
    ceo: "Karoly Borbely",
    headquarters: "Bucharest, Romania",
    description: "Romania's premier 100% green hydro producer and largest IPO in CEE history.",
    revenue: "€2.45B",
    netIncome: "€1.12B",
    peRatio: "10.1x",
    dividendYield: "8.4%",
    timeline: [
      { year: "2000", event: "Established as state hydro power producer." },
      { year: "2023", event: "Historic €1.9B IPO listing on BVB." },
    ],
  },
  {
    id: "comp-3",
    slug: "omv-petrom",
    symbol: "SNP",
    name: "OMV Petrom",
    sector: "Energy & Offshore Exploration",
    logo: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=300&auto=format&fit=crop",
    marketCap: "€8.2B",
    stockPrice: "0.7420 RON",
    priceChange: "+0.9%",
    isPositive: true,
    ceo: "Christina Verchere",
    headquarters: "Bucharest, Romania",
    description: "Largest integrated energy producer in Southeastern Europe, leading Neptun Deep offshore gas project.",
    revenue: "€7.80B",
    netIncome: "€820M",
    peRatio: "6.8x",
    dividendYield: "9.1%",
    timeline: [
      { year: "2004", event: "Privatization with OMV Group." },
      { year: "2024", event: "Final Investment Decision on Neptun Deep Black Sea gas." },
    ],
  },
  {
    id: "comp-4",
    slug: "one-united-properties",
    symbol: "ONE",
    name: "One United Properties",
    sector: "Luxury Real Estate Development",
    logo: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=300&auto=format&fit=crop",
    marketCap: "€780M",
    stockPrice: "0.9850 RON",
    priceChange: "+3.2%",
    isPositive: true,
    ceo: "Victor Căpitanu & Andrei Diaconescu",
    headquarters: "Bucharest, Romania",
    description: "Leading developer of premium green mixed-use residential and office developments in Bucharest.",
    revenue: "€310M",
    netIncome: "€95M",
    peRatio: "8.2x",
    dividendYield: "4.5%",
    timeline: [
      { year: "2009", event: "Co-founded by Victor Căpitanu and Andrei Diaconescu." },
      { year: "2021", event: "Successful IPO on BVB main market." },
    ],
  },
];

export const economicEvents: EconomicEvent[] = [
  {
    id: "ev-1",
    title: "BNR Monetary Policy Interest Rate Decision",
    date: "2026-08-08",
    time: "15:00 EEST",
    country: "RO",
    importance: "HIGH",
    actual: "6.50%",
    forecast: "6.50%",
    previous: "6.50%",
    category: "central-bank",
  },
  {
    id: "ev-2",
    title: "Romania CPI Inflation Rate (YoY)",
    date: "2026-08-12",
    time: "09:00 EEST",
    country: "RO",
    importance: "HIGH",
    forecast: "5.1%",
    previous: "5.5%",
    category: "macro",
  },
  {
    id: "ev-3",
    title: "ECB Governing Council Interest Rate Meeting",
    date: "2026-09-10",
    time: "15:15 CEST",
    country: "EU",
    importance: "HIGH",
    forecast: "3.25%",
    previous: "3.50%",
    category: "central-bank",
  },
  {
    id: "ev-4",
    title: "Banca Transilvania Q2 Financial Release & Dividend ex-Date",
    date: "2026-08-25",
    time: "08:30 EEST",
    country: "RO",
    importance: "MEDIUM",
    category: "dividends",
  },
];

export const aixBriefings: AiXBriefing[] = [
  {
    id: "brief-1",
    type: "morning",
    title: "AiX Morning Intelligence Briefing: August 5, 2026",
    date: "2026-08-05",
    whatChanged: [
      "BVB BET index posted a 2.3% gain, breaking past 18,420 points driven by energy listings.",
      "ROBOR 3M dropped to 5.58%, signaling further interbank rate stabilization.",
      "FDI figures released by BNR show a 14% year-on-year increase in private capital deployment.",
    ],
    whyItMatters: [
      "Equities are outperforming CEE regional peers, attracting increased Western European institutional flows.",
      "Falling interbank rates ease debt service burdens for corporate borrowers and mortgage holders.",
      "Long-term FDI confidence validates Romania's infrastructure and renewable energy convergence trajectory.",
    ],
    marketRecap: "Markets opened bullish across BVB indices. EUR/RON remains firmly pegged at 4.9765.",
  },
];
